import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'es' | 'pt-BR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.trading': 'Trading',
    'nav.positions': 'Positions',
    'nav.performance': 'Performance',
    'nav.portfolios': 'Portfolios',
    'nav.risk': 'Risk Management',
    'nav.news': 'News',
    'nav.assets': 'Asset Selection',
    'nav.operations': 'Operations',
    'nav.audit': 'Audit',
    'nav.backtest': 'Backtest',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.overview': 'Platform Overview',
    'admin.users_total': 'Total Users',
    'admin.users_beta': 'Beta Users',
    'admin.users_admins': 'Admins',
    'admin.beta_codes': 'Beta Codes',
    'admin.codes_active': 'Active Codes',
    'admin.codes_used': 'Total Uses',
    'admin.emails_title': 'Authorized Emails',
    'admin.emails_description': 'Pre-approved emails for beta access',
    'admin.email_add': 'Add Email',
    'admin.email_placeholder': 'email@example.com',
    'admin.notes_placeholder': 'Optional notes',
    'admin.users_title': 'Users',
    'admin.users_description': 'Manage platform users',
    'admin.codes_title': 'Beta Codes',
    'admin.codes_description': 'Manage beta invite codes',
    'admin.code_add': 'Create Code',
    'admin.code_placeholder': 'e.g. DELFOS-VIP-001',
    'admin.max_uses': 'Max Uses',
    'admin.expires': 'Expires',
    'admin.current_uses': 'Uses',
    'admin.status': 'Status',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.actions': 'Actions',
    'admin.deactivate': 'Deactivate',
    'admin.remove': 'Remove',
    'admin.approve': 'Approve Beta',
    'admin.make_admin': 'Make Admin',
    'admin.remove_admin': 'Remove Admin',
    'admin.no_emails': 'No authorized emails',
    'admin.no_codes': 'No beta codes',
    'admin.no_users': 'No users found',
    'admin.added_by': 'Added by',
    'admin.created_at': 'Created',
    'admin.never_expires': 'Never',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.portfolio_value': 'Portfolio Value',
    'dashboard.daily_pnl': 'Daily P&L',
    'dashboard.active_positions': 'Active Positions',
    'dashboard.total_trades': 'Total Trades',
    'dashboard.active_portfolios': 'Active portfolios',
    'dashboard.no_active_portfolio': 'No active portfolio',
    'dashboard.active_campaigns': 'Active Campaigns',
    'dashboard.open_positions': 'Open Positions',
    'dashboard.robots_trading': 'Robots trading automatically',
    'dashboard.across_campaigns': 'Across all campaigns',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.new_campaign': 'New Campaign',
    'dashboard.view_campaigns': 'View Campaigns',
    'dashboard.settings': 'Settings',
    'dashboard.recent_campaigns': 'Recent Campaigns',
    'dashboard.view_all': 'View All',
    'dashboard.no_campaigns': 'No campaigns yet',
    'dashboard.create_first': 'Create your first campaign',
    'dashboard.robot_activity': 'Robot Activity',
    'dashboard.no_activity': 'No recent activity',
    'dashboard.market_overview': 'Market Overview',
    'dashboard.campaigns.running': 'Running',
    'dashboard.campaigns.paused': 'Paused',
    'dashboard.campaigns.completed': 'Completed',
    'dashboard.campaigns.pending': 'Pending',
    'dashboard.profile.C': 'Conservative',
    'dashboard.profile.M': 'Moderate',
    'dashboard.profile.A': 'Aggressive',
    'dashboard.profile.conservative': 'Conservative',
    'dashboard.profile.moderate': 'Moderate',
    'dashboard.profile.aggressive': 'Aggressive',
    
    // Trading
    'trading.title': 'Trading',
    'trading.buy': 'Buy',
    'trading.sell': 'Sell',
    'trading.price': 'Price',
    'trading.amount': 'Amount',
    'trading.total': 'Total',
    'trading.order_book': 'Order Book',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.retry': 'Retry',
    
    // Auth
    'auth.login': 'Log In',
    'auth.welcome': 'Welcome to DELFOS',
    'auth.subtitle': 'Professional Crypto Trading Platform',

    // Asset Selection
    'assets.title': 'Asset Selection',
    'assets.description': 'Select top 100 tradable cryptocurrency pairs using quantitative filters and clustering',
    'assets.run_button': 'Run Selection',
    'assets.running': 'Running...',
    'assets.last_run': 'Last Run',
    'assets.never': 'Never',
    'assets.run_id': 'Run ID',
    'assets.assets_selected': 'Assets Selected',
    'assets.clusters': 'Clusters',
    'assets.no_data': 'No data available. Click "Run Selection" to start.',
    'assets.success_title': 'Asset Selection Complete',
    'assets.success_message': 'Selected {selected} assets from {total} candidates, clustered into {clusters} groups.',
    'assets.error_title': 'Selection Failed',
    'assets.error_message': 'Failed to run asset selection',
    'assets.top_100_title': 'TOP 100 Ranked Assets',
    'assets.rank': 'Rank',
    'assets.symbol': 'Symbol',
    'assets.score': 'Score',
    'assets.cluster': 'Cluster',
    'assets.no_rankings': 'No rankings available',
    'assets.running_title': 'Running Asset Selection',
    'assets.running_description': 'Analyzing 400+ cryptocurrency pairs with quantitative filters...',
    'assets.fetch_error': 'Failed to fetch rankings',
    'assets.cluster_prefix': 'C',
    'assets.no_cluster': '-',
    'assets.visualization.title': 'Cluster Visualization',
    'assets.visualization.description': 'Visual representation of asset clusters based on quantitative features',
    'assets.visualization.rank': 'Rank',
    'assets.visualization.score': 'Score',
    'assets.visualization.cluster': 'Cluster',
    'assets.visualization.normalized_rank': 'Normalized Rank',
    'assets.visualization.unclustered': 'Unclustered',
    'assets.filters.title': 'Tradability Filters',
    'assets.filters.description': 'Customize volume, spread, depth, and volatility thresholds for asset selection',
    'assets.filters.customized': 'Custom',
    'assets.filters.reset': 'Reset',
    'assets.filters.show': 'Show Filters',
    'assets.filters.hide': 'Hide Filters',
    'assets.filters.min_volume': 'Min Volume (24h)',
    'assets.filters.max_spread': 'Max Spread',
    'assets.filters.min_depth': 'Min Order Book Depth',
    'assets.filters.min_atr': 'Min Daily Volatility (ATR)',
    'assets.filters.default': 'Default',

    // Campaign
    'campaign.title': 'Campaigns',
    'campaign.subtitle': 'Manage and monitor your automated trading campaigns',
    'campaign.timeline': 'Campaign Timeline',
    'campaign.dayProgress': 'Day Progress',
    'campaign.day': 'Day',
    'campaign.daysRemaining': 'days remaining',
    'campaign.initialCapital': 'Initial Capital',
    'campaign.currentEquity': 'Current Equity',
    'campaign.finalEquity': 'Final Equity',
    'campaign.totalPnL': 'Total P&L',
    'campaign.drawdown': 'Drawdown',
    'campaign.drawdownBreached': 'Drawdown limit breached - Campaign stopped',
    'campaign.activeMessage': 'Campaign running within risk parameters',
    'campaign.errorLoading': 'Error loading campaign metrics',
    'campaign.noCampaign': 'No Active Campaign',
    'campaign.noCampaignDesc': 'Start a new campaign from the Portfolios page',
    'campaign.goToPortfolios': 'Go to Portfolios',
    'campaign.history': 'Campaign History',
    'campaign.pause': 'Pause',
    'campaign.resume': 'Resume',
    'campaign.stop': 'Stop',
    'campaign.rebalance': 'Rebalance',
    'campaign.paused': 'Campaign Paused',
    'campaign.pausedDesc': 'The campaign has been paused. Trading is stopped.',
    'campaign.resumed': 'Campaign Resumed',
    'campaign.resumedDesc': 'The campaign is now running again.',
    'campaign.stopped': 'Campaign Stopped',
    'campaign.stoppedDesc': 'The campaign has been stopped permanently.',
    'campaign.rebalanced': 'Rebalance Triggered',
    'campaign.rebalancedDesc': 'Portfolio rebalancing has started.',
    'campaign.delete': 'Delete',
    'campaign.deleted': 'Campaign Deleted',
    'campaign.deletedDesc': 'The campaign has been permanently deleted.',
    'campaign.deleteConfirmTitle': 'Delete Campaign',
    'campaign.deleteConfirmDesc': 'Are you sure you want to delete this campaign? This action cannot be undone.',
    'campaign.activeCampaigns': 'Active Campaigns',
    'campaign.pausedCampaigns': 'Paused Campaigns',
    'campaign.active': 'Active',
    'campaign.pausedStatus': 'Paused',
    'campaign.stoppedStatus': 'Stopped',
    'campaign.completedStatus': 'Completed',
    'campaign.createNew': 'Create New Campaign',
    'campaign.activeStatus': 'Active',
    'campaign.clusters': 'Clusters',
    'campaign.tradableAssets': 'tradable',

    // Campaign Detail
    'campaignDetail.notFound': 'Campaign not found',
    'campaignDetail.backToCampaigns': 'Back to Campaigns',
    'campaignDetail.tabs.universe': 'Asset Universe',
    'campaignDetail.tabs.positions': 'Positions',
    'campaignDetail.tabs.reports': 'Daily Reports',
    'campaignDetail.universe.title': 'Asset Universe',
    'campaignDetail.universe.description': 'Assets selected for this campaign based on K-means clustering',
    'campaignDetail.universe.total': 'Total',
    'campaignDetail.universe.tradable': 'Tradable',
    'campaignDetail.universe.active': 'Active',
    'campaignDetail.universe.inactive': 'Inactive',
    'campaignDetail.universe.problematic': 'Problematic',
    'campaignDetail.universe.clusters': 'Clusters',
    'campaignDetail.universe.searchPlaceholder': 'Search assets...',
    'campaignDetail.universe.filterStatus': 'Filter Status',
    'campaignDetail.universe.filterCluster': 'Filter Cluster',
    'campaignDetail.universe.allStatus': 'All Status',
    'campaignDetail.universe.allClusters': 'All Clusters',
    'campaignDetail.universe.noCluster': 'No Cluster',
    'campaignDetail.universe.rank': 'Rank',
    'campaignDetail.universe.symbol': 'Symbol',
    'campaignDetail.universe.cluster': 'Cluster',
    'campaignDetail.universe.score': 'Score',
    'campaignDetail.universe.weight': 'Weight',
    'campaignDetail.universe.status': 'Status',
    'campaignDetail.universe.empty': 'No assets in this campaign universe',
    'campaignDetail.positions.title': 'Trading Positions',
    'campaignDetail.positions.description': 'Open and closed positions for this campaign',
    'campaignDetail.positions.openPositions': 'Open Positions',
    'campaignDetail.positions.closedPositions': 'Closed Positions',
    'campaignDetail.positions.symbol': 'Symbol',
    'campaignDetail.positions.side': 'Side',
    'campaignDetail.positions.quantity': 'Quantity',
    'campaignDetail.positions.entryPrice': 'Entry Price',
    'campaignDetail.positions.currentPrice': 'Current Price',
    'campaignDetail.positions.stopLoss': 'Stop Loss',
    'campaignDetail.positions.takeProfit': 'Take Profit',
    'campaignDetail.positions.unrealizedPnl': 'Unrealized P&L',
    'campaignDetail.positions.realizedPnl': 'Realized P&L',
    'campaignDetail.positions.openedAt': 'Opened',
    'campaignDetail.positions.closedAt': 'Closed',
    'campaignDetail.positions.closeReason': 'Close Reason',
    'campaignDetail.positions.noOpenPositions': 'No open positions',
    'campaignDetail.positions.noClosedPositions': 'No closed positions',
    'campaignDetail.positions.long': 'LONG',
    'campaignDetail.positions.short': 'SHORT',
    'campaignDetail.positions.tp': 'Take Profit',
    'campaignDetail.positions.sl': 'Stop Loss',
    'campaignDetail.positions.manual': 'Manual',
    'campaignDetail.positions.expired': 'Expired',
    'campaignDetail.reports.comingSoon': 'Reports tab coming soon',

    // Campaign Wizard
    'wizard.title': 'Create New Campaign',
    'wizard.subtitle': 'Follow the steps to configure and launch your trading campaign',
    'wizard.menuItem': 'New Campaign',
    'wizard.step.basics': 'Basics',
    'wizard.step.mode': 'Mode',
    'wizard.step.portfolio': 'Portfolio',
    'wizard.step.risk': 'Risk',
    'wizard.step.review': 'Review',
    'wizard.step1.title': 'Basic Information',
    'wizard.step1.description': 'Set the name, profile, capital, and duration for your campaign',
    'wizard.step2.title': 'Trading Mode',
    'wizard.step2.description': 'Choose between paper trading (simulation) or live trading',
    'wizard.step3.title': 'Select Portfolio',
    'wizard.step3.description': 'Choose the portfolio this campaign will trade with',
    'wizard.step4.title': 'Risk Configuration',
    'wizard.step4.description': 'Set your risk limits and circuit breaker thresholds',
    'wizard.step5.title': 'Review & Activate',
    'wizard.step5.description': 'Review your settings and AI analysis before launching',
    'wizard.selectProfile': 'Select Campaign Profile',
    'wizard.selectProfileDesc': 'Choose a risk profile that defines the operational behavior and aggressiveness of the trading strategy. Each profile has pre-configured risk parameters.',
    'wizard.riskPerTrade': 'Risk/Trade',
    'wizard.maxPositions': 'Max Positions',
    'wizard.tpMultiplier': 'Take Profit',
    'wizard.noProfiles': 'No risk profiles available. Contact support.',
    'wizard.campaignName': 'Campaign Name',
    'wizard.campaignNamePlaceholder': 'My December Campaign',
    'wizard.initialCapital': 'Initial Capital',
    'wizard.minCapitalHint': 'Minimum $10 USD',
    'wizard.duration': 'Campaign Duration',
    'wizard.days': 'days',
    'wizard.recommended': 'recommended',
    'wizard.paperMode': 'Paper Trading',
    'wizard.paperModeDesc': 'Practice trading with simulated money. No real funds at risk.',
    'wizard.liveMode': 'Live Trading',
    'wizard.liveModeDesc': 'Trade with real money on Kraken exchange. Real profits and losses.',
    'wizard.noRiskBadge': 'No Risk',
    'wizard.realMoneyBadge': 'Real Money',
    'wizard.krakenValidation': 'Kraken API Status',
    'wizard.krakenValid': 'Kraken API configured and valid',
    'wizard.krakenInvalid': 'Kraken API not configured',
    'wizard.configureKraken': 'Configure in Settings',
    'wizard.livePortfolioWarning': 'This portfolio uses Live Trading mode',
    'wizard.noPortfolios': 'No portfolios available. Create one first.',
    'wizard.createPortfolio': 'Create Portfolio',
    'wizard.maxDrawdown': 'Maximum Drawdown Limit',
    'wizard.maxDrawdownDesc': 'Campaign will automatically stop if losses exceed this percentage',
    'wizard.circuitBreaker': 'Circuit Breaker',
    'wizard.protectionsEnabled': 'Protections Enabled',
    'wizard.protection1': '3-layer circuit breaker system (asset, cluster, global)',
    'wizard.protection2': 'ATR-based Stop Loss and Take Profit',
    'wizard.protection3': 'Real-time staleness monitoring',
    'wizard.mode': 'Trading Mode',
    'wizard.portfolio': 'Portfolio',
    'wizard.readyToLaunch': 'Ready to Launch',
    'wizard.launchDescription': 'Your campaign will start immediately after activation. You can pause or stop it at any time from the Campaigns page.',
    'wizard.previous': 'Previous',
    'wizard.next': 'Next',
    'wizard.activateCampaign': 'Activate Campaign',
    'wizard.success': 'Success',
    'wizard.campaignCreated': 'Your campaign has been created and is now active!',
    'wizard.createError': 'Failed to create campaign. Please try again.',
    'wizard.profilesLoadError': 'Failed to load risk profiles. Please refresh the page.',
    'wizard.retry': 'Try Again',
    'wizard.validation.nameRequired': 'Please enter a campaign name',
    'wizard.validation.minCapital': 'Minimum capital is $10 USD',
    'wizard.validation.krakenRequired': 'Live mode requires valid Kraken API credentials',
    'wizard.validation.portfolioRequired': 'Please select a portfolio',
    'wizard.aiSuggest': 'AI Suggestion',
    'wizard.aiSuggestionReady': 'AI Recommendation Ready',
    'wizard.aiSuggestionDesc': 'Review the suggested risk parameters below',
    'wizard.aiSuggestionError': 'Failed to get AI suggestion',
    'wizard.aiRecommendation': 'AI Recommendation',
    'wizard.suggestedDrawdown': 'Suggested Drawdown',
    'wizard.aiTips': 'Tips',
    'wizard.applySuggestion': 'Apply Suggestion',
    'wizard.suggestionApplied': 'Suggestion Applied',
    'wizard.risk.conservative': 'Conservative',
    'wizard.risk.moderate': 'Moderate',
    'wizard.risk.aggressive': 'Aggressive',
    'wizard.market.status.healthy': 'Market Healthy',
    'wizard.market.status.warning': 'Market Warning',
    'wizard.market.status.critical': 'Market Critical',
    'wizard.market.dataQuality': 'Data Quality',
    'wizard.market.activeSymbols': 'Active Symbols',
    'wizard.market.staleness': 'Avg Staleness',
    'wizard.market.volatility': 'Volatility',
    'wizard.market.avgVolatility': 'Average Volatility',
    'wizard.market.level': 'Level',
    'wizard.market.circuitBreakers': 'Circuit Breakers',
    'wizard.market.tradingAllowed': 'Trading Allowed',
    'wizard.market.tradingBlocked': 'Trading Blocked',
    'wizard.market.topVolatile': 'Most Volatile Assets',
    'wizard.market.noData': 'Market data unavailable',
    'wizard.aiAnalyzing': 'AI Analyzing...',
    'wizard.aiAnalyzingDesc': 'Generating campaign analysis',
    'wizard.aiSummary': 'AI Analysis',
    'wizard.pros': 'Advantages',
    'wizard.cons': 'Considerations',

    // Costs & Taxes
    'costs.title': 'Costs & Taxes',
    'costs.subtitle': 'Track trading costs impact and tax obligations',
    'costs.impact': 'Cost Impact Analysis',
    'costs.impactDescription': 'See how fees, slippage, and taxes affect your profits',
    'costs.totalFees': 'Total Fees',
    'costs.totalSlippage': 'Total Slippage',
    'costs.totalTaxes': 'Total Taxes',
    'costs.totalCosts': 'Total Costs',
    'costs.netProfit': 'Net Profit',
    'costs.grossProfit': 'Gross Profit',
    'costs.impactOnProfit': 'Impact on Profit',
    'costs.breakdown': 'Cost Breakdown',
    'costs.noData': 'No cost data available for the selected period',
    'costs.period': 'Period',
    'costs.trades': 'Trades',
    'costs.profitableTrades': 'Profitable Trades',
    'costs.effectiveRate': 'Effective Tax Rate',

    // Tax Profile
    'tax.profile': 'Tax Profile',
    'tax.profileDescription': 'Configure your tax settings based on your country',
    'tax.country': 'Country/Region',
    'tax.regime': 'Tax Regime',
    'tax.year': 'Tax Year',
    'tax.shortTermRate': 'Short-term Rate',
    'tax.longTermRate': 'Long-term Rate',
    'tax.minimumTaxable': 'Minimum Taxable',
    'tax.saveProfile': 'Save Profile',
    'tax.profileSaved': 'Tax profile saved successfully',
    'tax.profileError': 'Failed to save tax profile',
    'tax.noProfile': 'No tax profile configured',
    'tax.suggestLocation': 'Suggested based on your location',
    'tax.acceptSuggestion': 'Accept Suggestion',
    'tax.configureManually': 'Configure Manually',

    // Tax Regimes
    'tax.regime.BR': 'Brazil - Day Trading (15% daily)',
    'tax.regime.US': 'United States - Capital Gains',
    'tax.regime.EU': 'European Union - Capital Gains',
    'tax.regime.AE': 'UAE - Tax Exempt',
    'tax.regime.SG': 'Singapore - Tax Exempt',

    // Tooltips
    'tooltip.slippage': 'Slippage is the difference between the expected price and the actual executed price',
    'tooltip.makerFee': 'Maker fee is charged when you add liquidity to the order book (limit orders)',
    'tooltip.takerFee': 'Taker fee is charged when you remove liquidity from the order book (market orders)',
    'tooltip.fees': 'Trading fees charged by the exchange for executing your orders',
    'tooltip.taxes': 'Taxes owed based on your configured tax profile and realized profits',
    'tooltip.netProfit': 'Final profit after deducting all fees, slippage, and taxes',
    'tooltip.grossProfit': 'Total profit before deducting costs and taxes',
    'tooltip.dailyNetting': 'Brazil tax regime: Profits and losses are netted daily before calculating 15% tax',
    'tooltip.perTrade': 'Tax calculated on each individual trade based on realized profit',
    'tooltip.taxExempt': 'This region does not tax cryptocurrency trading profits',

    // Compliance Report
    'report.title': 'Compliance Report',
    'report.description': 'Export detailed reports for tax filing and compliance',
    'report.export': 'Export Report',
    'report.exportCSV': 'Export CSV',
    'report.exportPDF': 'Export PDF',
    'report.generating': 'Generating report...',
    'report.success': 'Report generated successfully',
    'report.error': 'Failed to generate report',
    'report.period': 'Report Period',
    'report.summary': 'Summary',
    'report.details': 'Trade Details',

    // Operations (Runbook)
    'operations.title': 'Operational Flow',
    'operations.subtitle': 'Daily trading cycle timeline and status',
    'operations.never': 'Never',
    'operations.nextRebalance': 'Next Rebalance',
    'operations.assetsSelected': 'Assets Selected',
    'operations.of100': 'of 100 max',
    'operations.activePositions': 'Active Positions',
    'operations.openPositions': 'Open positions',
    'operations.dailyPnL': 'Daily P&L',
    'operations.today': 'Today',
    'operations.dataStatus': 'Data Status',
    'operations.dataQuality': 'Data quality',
    'operations.cycleProgress': 'Cycle Progress',
    'operations.lastRun': 'Last run',
    'operations.lastExecution': 'Last execution time',

    'operations.timeline.title': 'Daily Runbook Timeline',
    'operations.timeline.description': 'Operational cycle: Selection, Distribution, Trading, Rebalance, Audit',

    'operations.selection.title': 'Global Selection',
    'operations.selection.description': 'Run ranking + K-means clustering to select top 100 assets',
    'operations.distribution.title': 'Distribution',
    'operations.distribution.description': 'Calculate sizing with costs (Fee_avg, Slippage_avg), apply cluster and global caps',
    'operations.trading.title': 'Trading',
    'operations.trading.time': 'Throughout the day',
    'operations.trading.description': 'Signals, OCO orders, stops, trailing, profit reallocation, staleness monitoring',
    'operations.rebalance.title': 'Rebalance',
    'operations.rebalance.time': 'Every 8h',
    'operations.rebalance.description': 'Re-ranking, asset swap, recalculate positions',
    'operations.audit.title': 'Audit',
    'operations.audit.time': 'Every 24h',
    'operations.audit.description': 'Performance metrics: hit rate, payoff, PnL, VaR/ES, costs, slippage',

    'operations.status.completed': 'Done',
    'operations.status.active': 'Active',
    'operations.status.degraded': 'Degraded',
    'operations.status.pending': 'Pending',

    'operations.staleness.fresh': 'Fresh',
    'operations.staleness.warn': 'Warning',
    'operations.staleness.hard': 'Stale',
    'operations.staleness.kill_switch': 'Critical',

    'operations.tradingWindow.title': 'Trading Window',
    'operations.tradingWindow.signals': 'Signal Generation',
    'operations.tradingWindow.active': 'Active',
    'operations.tradingWindow.paused': 'Paused',
    'operations.tradingWindow.oco': 'OCO Orders',
    'operations.tradingWindow.ocoEnabled': 'Enabled',
    'operations.tradingWindow.staleness': 'Staleness Monitor',

    'operations.rebalanceInfo.title': 'Rebalance Schedule',
    'operations.rebalanceInfo.interval': 'Interval',
    'operations.rebalanceInfo.lastRun': 'Last Run',
    'operations.rebalanceInfo.nextRun': 'Next Run',

    // Audit Dashboard
    'audit.title': 'Audit Dashboard',
    'audit.subtitle': '24-hour consolidated performance metrics',
    'audit.period': 'Period',
    'audit.performance': 'Performance Metrics',
    'audit.hitRate': 'Hit Rate',
    'audit.trades': 'trades',
    'audit.wins': 'wins',
    'audit.losses': 'losses',
    'audit.profitFactor': 'Profit Factor',
    'audit.excellent': 'Excellent',
    'audit.good': 'Good',
    'audit.poor': 'Poor',
    'audit.avgWin': 'Avg Win',
    'audit.avgLoss': 'Avg Loss',
    'audit.pnlSection': 'P&L Summary',
    'audit.totalPnL': 'Total P&L',
    'audit.realized': 'Realized',
    'audit.unrealized': 'Unrealized',
    'audit.equity': 'Current Equity',
    'audit.riskSection': 'Risk Metrics',
    'audit.var95': 'VaR 95%',
    'audit.var95Desc': '5% worst-case loss',
    'audit.expectedShortfall': 'Expected Shortfall',
    'audit.esDesc': 'Average tail loss',
    'audit.maxDrawdown': 'Max Drawdown',
    'audit.drawdownDesc': 'Peak-to-trough decline',
    'audit.costsSection': 'Trading Costs',
    'audit.totalFees': 'Total Fees',
    'audit.slippage': 'Slippage',
    'audit.totalCosts': 'Total Costs',
    'audit.costPerTrade': 'Cost per Trade',
    'audit.lastUpdated': 'Last updated',
    
    // Backtest translations
    'backtest.title': 'Backtest & Simulation',
    'backtest.subtitle': 'Historical testing with Monte Carlo stress analysis',
    'backtest.newBacktest': 'New Backtest',
    'backtest.history': 'Backtest History',
    'backtest.configuration': 'Configuration',
    'backtest.name': 'Backtest Name',
    'backtest.namePlaceholder': 'My backtest analysis',
    'backtest.period': 'Analysis Period',
    'backtest.startDate': 'Start Date',
    'backtest.endDate': 'End Date',
    'backtest.initialCapital': 'Initial Capital',
    'backtest.symbols': 'Symbols',
    'backtest.symbolsPlaceholder': 'BTC/USD, ETH/USD',
    'backtest.applyBreakers': 'Apply Circuit Breakers',
    'backtest.applyBreakersDesc': 'Enable 3-layer risk management (asset, cluster, global)',
    'backtest.strategyParams': 'Strategy Parameters',
    'backtest.riskParams': 'Risk Parameters',
    'backtest.costParams': 'Cost Parameters',
    'backtest.runBacktest': 'Run Backtest',
    'backtest.running': 'Running...',
    'backtest.status': 'Status',
    'backtest.pending': 'Pending',
    'backtest.completed': 'Completed',
    'backtest.failed': 'Failed',
    'backtest.progress': 'Progress',
    'backtest.results': 'Results',
    'backtest.noBacktests': 'No backtests yet. Run your first simulation above.',
    'backtest.metrics.title': 'Performance Metrics',
    'backtest.metrics.hitRate': 'Hit Rate',
    'backtest.metrics.profitFactor': 'Profit Factor',
    'backtest.metrics.payoffRatio': 'Payoff Ratio',
    'backtest.metrics.expectancy': 'Expectancy',
    'backtest.metrics.avgWin': 'Avg Win',
    'backtest.metrics.avgLoss': 'Avg Loss',
    'backtest.metrics.sharpe': 'Sharpe Ratio',
    'backtest.metrics.sortino': 'Sortino Ratio',
    'backtest.metrics.var95': 'VaR 95%',
    'backtest.metrics.var99': 'VaR 99%',
    'backtest.metrics.es95': 'ES 95%',
    'backtest.metrics.es99': 'ES 99%',
    'backtest.metrics.maxDrawdown': 'Max Drawdown',
    'backtest.metrics.turnover': 'Turnover',
    'backtest.metrics.fees': 'Fees',
    'backtest.metrics.slippage': 'Slippage',
    'backtest.metrics.costDrag': 'Cost Drag',
    'backtest.monteCarlo.title': 'Monte Carlo Simulation',
    'backtest.monteCarlo.scenarios': 'Scenarios',
    'backtest.monteCarlo.meanEquity': 'Mean Final Equity',
    'backtest.monteCarlo.stdEquity': 'Std Dev Equity',
    'backtest.monteCarlo.probPositive': 'Prob. Positive PnL',
    'backtest.monteCarlo.probExceed10DD': 'Prob. >10% Drawdown',
    'backtest.monteCarlo.confidenceInterval': '95% Confidence Interval',
    'backtest.validation.title': 'Validation Criteria',
    'backtest.validation.es95Improved': 'ES95 Improved with Breakers',
    'backtest.validation.var99Improved': 'VaR99 Reduced in Stress',
    'backtest.validation.pnlPositive': 'Net PnL Positive',
    'backtest.validation.passed': 'Validation PASSED',
    'backtest.validation.failed': 'Validation FAILED',
    'backtest.validation.notes': 'Validation Notes',
    'backtest.breakers.title': 'Circuit Breaker Statistics',
    'backtest.breakers.assetTriggered': 'Asset Breakers Triggered',
    'backtest.breakers.clusterTriggered': 'Cluster Breakers Triggered',
    'backtest.breakers.globalTriggered': 'Global Breakers Triggered',
    'backtest.breakers.tradesBlocked': 'Trades Blocked',
    'backtest.trades.title': 'Recent Trades',
    'backtest.trades.symbol': 'Symbol',
    'backtest.trades.side': 'Side',
    'backtest.trades.entry': 'Entry',
    'backtest.trades.exit': 'Exit',
    'backtest.trades.pnl': 'PnL',
    'backtest.trades.reason': 'Exit Reason',

    // Robot Activity Feed
    'robot.feed.title': 'Robot Activity',
    'robot.feed.empty': 'No robot activity yet',
    'robot.feed.waiting': 'Waiting for trading signals...',
    'robot.feed.error': 'Failed to load activities',
    'robot.severity.success': 'Success',
    'robot.severity.warning': 'Warning',
    'robot.severity.error': 'Error',
    'robot.severity.info': 'Info',
    'robot.signal.long': 'LONG signal detected',
    'robot.signal.short': 'SHORT signal detected',
    'robot.signal.neutral': 'No signal (neutral)',
    'robot.position.open.long': 'Opened LONG position',
    'robot.position.open.short': 'Opened SHORT position',
    'robot.position.close.sl_hit': 'Position closed - Stop Loss hit',
    'robot.position.close.tp_hit': 'Position closed - Take Profit hit',
    'robot.position.close.signal_exit': 'Position closed - Signal exit',
    'robot.position.close.rebalance_exit': 'Position closed - Rebalance',
    'robot.position.close.breaker_exit': 'Position closed - Circuit breaker',
    'robot.position.close.manual': 'Position closed - Manual',
    'robot.breaker.pair.triggered': 'Pair circuit breaker TRIGGERED',
    'robot.breaker.pair.warning': 'Pair circuit breaker warning',
    'robot.breaker.daily.triggered': 'Daily circuit breaker TRIGGERED',
    'robot.breaker.daily.warning': 'Daily loss limit warning',
    'robot.breaker.campaign.triggered': 'Campaign circuit breaker TRIGGERED',
    'robot.breaker.campaign.warning': 'Drawdown limit warning',
    'robot.rebalance.complete': '8-hour rebalance complete',
    'robot.scan.signals_found': 'Market scan: Signals found',
    'robot.scan.no_signals': 'Market scan: No signals',
    'robot.details.signal': 'Signal',
    'robot.details.price': 'Price',
    'robot.details.side': 'Side',
    'robot.details.entry': 'Entry',
    'robot.details.exit': 'Exit',
    'robot.details.reason': 'Reason',
    'robot.details.type': 'Type',
    'robot.details.threshold': 'Threshold',
    'robot.details.current': 'Current',
    'robot.details.tradable': 'Tradable assets',
    'robot.details.added': 'Added',
    'robot.details.removed': 'Removed',
    'robot.details.scanned': 'Scanned',
    'robot.details.signals': 'Signals',
    'campaignDetail.tabs.activity': 'Activity',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.trading': 'Trading',
    'nav.positions': 'Posiciones',
    'nav.performance': 'Rendimiento',
    'nav.portfolios': 'Carteras',
    'nav.risk': 'Gestión de Riesgo',
    'nav.news': 'Noticias',
    'nav.assets': 'Selección de Activos',
    'nav.operations': 'Operaciones',
    'nav.audit': 'Auditoría',
    'nav.backtest': 'Backtest',
    'nav.settings': 'Configuración',
    'nav.admin': 'Admin',
    'nav.logout': 'Cerrar Sesión',
    
    // Admin Dashboard
    'admin.title': 'Panel de Administración',
    'admin.overview': 'Resumen de la Plataforma',
    'admin.users_total': 'Usuarios Totales',
    'admin.users_beta': 'Usuarios Beta',
    'admin.users_admins': 'Administradores',
    'admin.beta_codes': 'Códigos Beta',
    'admin.codes_active': 'Códigos Activos',
    'admin.codes_used': 'Usos Totales',
    'admin.emails_title': 'Emails Autorizados',
    'admin.emails_description': 'Emails pre-aprobados para acceso beta',
    'admin.email_add': 'Agregar Email',
    'admin.email_placeholder': 'email@ejemplo.com',
    'admin.notes_placeholder': 'Notas opcionales',
    'admin.users_title': 'Usuarios',
    'admin.users_description': 'Gestionar usuarios de la plataforma',
    'admin.codes_title': 'Códigos Beta',
    'admin.codes_description': 'Gestionar códigos de invitación beta',
    'admin.code_add': 'Crear Código',
    'admin.code_placeholder': 'ej. DELFOS-VIP-001',
    'admin.max_uses': 'Usos Máx',
    'admin.expires': 'Expira',
    'admin.current_uses': 'Usos',
    'admin.status': 'Estado',
    'admin.active': 'Activo',
    'admin.inactive': 'Inactivo',
    'admin.actions': 'Acciones',
    'admin.deactivate': 'Desactivar',
    'admin.remove': 'Eliminar',
    'admin.approve': 'Aprobar Beta',
    'admin.make_admin': 'Hacer Admin',
    'admin.remove_admin': 'Quitar Admin',
    'admin.no_emails': 'Sin emails autorizados',
    'admin.no_codes': 'Sin códigos beta',
    'admin.no_users': 'Sin usuarios encontrados',
    'admin.added_by': 'Agregado por',
    'admin.created_at': 'Creado',
    'admin.never_expires': 'Nunca',
    
    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.portfolio_value': 'Valor del Portafolio',
    'dashboard.daily_pnl': 'P&G Diario',
    'dashboard.active_positions': 'Posiciones Activas',
    'dashboard.total_trades': 'Total de Operaciones',
    'dashboard.active_portfolios': 'Portafolios activos',
    'dashboard.no_active_portfolio': 'Sin portafolio activo',
    'dashboard.active_campaigns': 'Campañas Activas',
    'dashboard.open_positions': 'Posiciones Abiertas',
    'dashboard.robots_trading': 'Robots operando automáticamente',
    'dashboard.across_campaigns': 'En todas las campañas',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.new_campaign': 'Nueva Campaña',
    'dashboard.view_campaigns': 'Ver Campañas',
    'dashboard.settings': 'Configuración',
    'dashboard.recent_campaigns': 'Campañas Recientes',
    'dashboard.view_all': 'Ver Todas',
    'dashboard.no_campaigns': 'Sin campañas aún',
    'dashboard.create_first': 'Crea tu primera campaña',
    'dashboard.robot_activity': 'Actividad del Robot',
    'dashboard.no_activity': 'Sin actividad reciente',
    'dashboard.market_overview': 'Resumen del Mercado',
    'dashboard.campaigns.running': 'Ejecutando',
    'dashboard.campaigns.paused': 'Pausado',
    'dashboard.campaigns.completed': 'Completado',
    'dashboard.campaigns.pending': 'Pendiente',
    'dashboard.profile.C': 'Conservador',
    'dashboard.profile.M': 'Moderado',
    'dashboard.profile.A': 'Agresivo',
    'dashboard.profile.conservative': 'Conservador',
    'dashboard.profile.moderate': 'Moderado',
    'dashboard.profile.aggressive': 'Agresivo',
    
    // Trading
    'trading.title': 'Trading',
    'trading.buy': 'Comprar',
    'trading.sell': 'Vender',
    'trading.price': 'Precio',
    'trading.amount': 'Cantidad',
    'trading.total': 'Total',
    'trading.order_book': 'Libro de Órdenes',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    'common.retry': 'Reintentar',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.welcome': 'Bienvenido a DELFOS',
    'auth.subtitle': 'Plataforma Profesional de Trading de Criptomonedas',

    // Asset Selection
    'assets.title': 'Selección de Activos',
    'assets.description': 'Seleccionar los 100 pares de criptomonedas más negociables usando filtros cuantitativos y clustering',
    'assets.run_button': 'Ejecutar Selección',
    'assets.running': 'Ejecutando...',
    'assets.last_run': 'Última Ejecución',
    'assets.never': 'Nunca',
    'assets.run_id': 'ID de Ejecución',
    'assets.assets_selected': 'Activos Seleccionados',
    'assets.clusters': 'Clusters',
    'assets.no_data': 'No hay datos disponibles. Haga clic en "Ejecutar Selección" para comenzar.',
    'assets.success_title': 'Selección Completada',
    'assets.success_message': 'Seleccionados {selected} activos de {total} candidatos, agrupados en {clusters} clusters.',
    'assets.error_title': 'Selección Fallida',
    'assets.error_message': 'Error al ejecutar la selección de activos',
    'assets.top_100_title': 'TOP 100 Activos Clasificados',
    'assets.rank': 'Rango',
    'assets.symbol': 'Símbolo',
    'assets.score': 'Puntuación',
    'assets.cluster': 'Cluster',
    'assets.no_rankings': 'No hay clasificaciones disponibles',
    'assets.running_title': 'Ejecutando Selección de Activos',
    'assets.running_description': 'Analizando más de 400 pares de criptomonedas con filtros cuantitativos...',
    'assets.fetch_error': 'Error al obtener clasificaciones',
    'assets.cluster_prefix': 'C',
    'assets.no_cluster': '-',
    'assets.visualization.title': 'Visualización de Clusters',
    'assets.visualization.description': 'Representación visual de clusters de activos basada en características cuantitativas',
    'assets.visualization.rank': 'Rango',
    'assets.visualization.score': 'Puntuación',
    'assets.visualization.cluster': 'Cluster',
    'assets.visualization.normalized_rank': 'Rango Normalizado',
    'assets.visualization.unclustered': 'Sin Cluster',
    'assets.filters.title': 'Filtros de Negociabilidad',
    'assets.filters.description': 'Personalizar umbrales de volumen, spread, profundidad y volatilidad para la selección de activos',
    'assets.filters.customized': 'Personalizado',
    'assets.filters.reset': 'Restablecer',
    'assets.filters.show': 'Mostrar Filtros',
    'assets.filters.hide': 'Ocultar Filtros',
    'assets.filters.min_volume': 'Volumen Mín (24h)',
    'assets.filters.max_spread': 'Spread Máx',
    'assets.filters.min_depth': 'Profundidad Mín del Libro',
    'assets.filters.min_atr': 'Volatilidad Diaria Mín (ATR)',
    'assets.filters.default': 'Por defecto',

    // Campaign
    'campaign.title': 'Campañas',
    'campaign.subtitle': 'Gestione y supervise sus campañas de trading automatizado',
    'campaign.timeline': 'Cronograma de Campaña',
    'campaign.dayProgress': 'Progreso del Día',
    'campaign.day': 'Día',
    'campaign.daysRemaining': 'días restantes',
    'campaign.initialCapital': 'Capital Inicial',
    'campaign.currentEquity': 'Capital Actual',
    'campaign.finalEquity': 'Capital Final',
    'campaign.totalPnL': 'P&G Total',
    'campaign.drawdown': 'Drawdown',
    'campaign.drawdownBreached': 'Límite de drawdown superado - Campaña detenida',
    'campaign.activeMessage': 'Campaña en ejecución dentro de los parámetros de riesgo',
    'campaign.errorLoading': 'Error al cargar métricas de campaña',
    'campaign.noCampaign': 'Sin Campaña Activa',
    'campaign.noCampaignDesc': 'Inicie una nueva campaña desde la página de Portafolios',
    'campaign.goToPortfolios': 'Ir a Portafolios',
    'campaign.history': 'Historial de Campañas',
    'campaign.pause': 'Pausar',
    'campaign.resume': 'Reanudar',
    'campaign.stop': 'Detener',
    'campaign.rebalance': 'Rebalancear',
    'campaign.paused': 'Campaña Pausada',
    'campaign.pausedDesc': 'La campaña ha sido pausada. El trading está detenido.',
    'campaign.resumed': 'Campaña Reanudada',
    'campaign.resumedDesc': 'La campaña está funcionando de nuevo.',
    'campaign.stopped': 'Campaña Detenida',
    'campaign.stoppedDesc': 'La campaña ha sido detenida permanentemente.',
    'campaign.rebalanced': 'Rebalanceo Iniciado',
    'campaign.rebalancedDesc': 'El rebalanceo del portafolio ha comenzado.',
    'campaign.delete': 'Eliminar',
    'campaign.deleted': 'Campaña Eliminada',
    'campaign.deletedDesc': 'La campaña ha sido eliminada permanentemente.',
    'campaign.deleteConfirmTitle': 'Eliminar Campaña',
    'campaign.deleteConfirmDesc': 'Estas seguro de que deseas eliminar esta campana? Esta accion no se puede deshacer.',
    'campaign.activeCampaigns': 'Campañas Activas',
    'campaign.pausedCampaigns': 'Campañas Pausadas',
    'campaign.active': 'Activa',
    'campaign.pausedStatus': 'Pausada',
    'campaign.stoppedStatus': 'Detenida',
    'campaign.completedStatus': 'Completada',
    'campaign.createNew': 'Crear Nueva Campaña',
    'campaign.activeStatus': 'Activa',
    'campaign.clusters': 'Clusters',
    'campaign.tradableAssets': 'negociables',

    // Campaign Detail
    'campaignDetail.notFound': 'Campaña no encontrada',
    'campaignDetail.backToCampaigns': 'Volver a Campañas',
    'campaignDetail.tabs.universe': 'Universo de Activos',
    'campaignDetail.tabs.positions': 'Posiciones',
    'campaignDetail.tabs.reports': 'Reportes Diarios',
    'campaignDetail.universe.title': 'Universo de Activos',
    'campaignDetail.universe.description': 'Activos seleccionados para esta campaña basados en clustering K-means',
    'campaignDetail.universe.total': 'Total',
    'campaignDetail.universe.tradable': 'Negociables',
    'campaignDetail.universe.active': 'Activos',
    'campaignDetail.universe.inactive': 'Inactivos',
    'campaignDetail.universe.problematic': 'Problemáticos',
    'campaignDetail.universe.clusters': 'Clusters',
    'campaignDetail.universe.searchPlaceholder': 'Buscar activos...',
    'campaignDetail.universe.filterStatus': 'Filtrar Estado',
    'campaignDetail.universe.filterCluster': 'Filtrar Cluster',
    'campaignDetail.universe.allStatus': 'Todos los Estados',
    'campaignDetail.universe.allClusters': 'Todos los Clusters',
    'campaignDetail.universe.noCluster': 'Sin Cluster',
    'campaignDetail.universe.rank': 'Rango',
    'campaignDetail.universe.symbol': 'Símbolo',
    'campaignDetail.universe.cluster': 'Cluster',
    'campaignDetail.universe.score': 'Puntuación',
    'campaignDetail.universe.weight': 'Peso',
    'campaignDetail.universe.status': 'Estado',
    'campaignDetail.universe.empty': 'No hay activos en el universo de esta campaña',
    'campaignDetail.positions.title': 'Posiciones de Trading',
    'campaignDetail.positions.description': 'Posiciones abiertas y cerradas para esta campaña',
    'campaignDetail.positions.openPositions': 'Posiciones Abiertas',
    'campaignDetail.positions.closedPositions': 'Posiciones Cerradas',
    'campaignDetail.positions.symbol': 'Símbolo',
    'campaignDetail.positions.side': 'Lado',
    'campaignDetail.positions.quantity': 'Cantidad',
    'campaignDetail.positions.entryPrice': 'Precio Entrada',
    'campaignDetail.positions.currentPrice': 'Precio Actual',
    'campaignDetail.positions.stopLoss': 'Stop Loss',
    'campaignDetail.positions.takeProfit': 'Take Profit',
    'campaignDetail.positions.unrealizedPnl': 'P&L No Realizado',
    'campaignDetail.positions.realizedPnl': 'P&L Realizado',
    'campaignDetail.positions.openedAt': 'Abierta',
    'campaignDetail.positions.closedAt': 'Cerrada',
    'campaignDetail.positions.closeReason': 'Razón de Cierre',
    'campaignDetail.positions.noOpenPositions': 'Sin posiciones abiertas',
    'campaignDetail.positions.noClosedPositions': 'Sin posiciones cerradas',
    'campaignDetail.positions.long': 'COMPRA',
    'campaignDetail.positions.short': 'VENTA',
    'campaignDetail.positions.tp': 'Take Profit',
    'campaignDetail.positions.sl': 'Stop Loss',
    'campaignDetail.positions.manual': 'Manual',
    'campaignDetail.positions.expired': 'Expirada',
    'campaignDetail.reports.comingSoon': 'Pestaña de reportes próximamente',

    // Campaign Wizard
    'wizard.title': 'Crear Nueva Campaña',
    'wizard.subtitle': 'Siga los pasos para configurar y lanzar su campaña de trading',
    'wizard.menuItem': 'Nueva Campaña',
    'wizard.step.basics': 'Básicos',
    'wizard.step.mode': 'Modo',
    'wizard.step.portfolio': 'Portafolio',
    'wizard.step.risk': 'Riesgo',
    'wizard.step.review': 'Revisar',
    'wizard.step1.title': 'Información Básica',
    'wizard.step1.description': 'Configure el nombre, perfil, capital y duración de su campaña',
    'wizard.step2.title': 'Modo de Trading',
    'wizard.step2.description': 'Elija entre paper trading (simulación) o trading real',
    'wizard.step3.title': 'Seleccionar Portafolio',
    'wizard.step3.description': 'Elija el portafolio con el que operará esta campaña',
    'wizard.step4.title': 'Configuración de Riesgo',
    'wizard.step4.description': 'Configure sus límites de riesgo y umbrales de circuit breaker',
    'wizard.step5.title': 'Revisar y Activar',
    'wizard.step5.description': 'Revise su configuración y análisis IA antes de lanzar',
    'wizard.selectProfile': 'Seleccionar Perfil de Campaña',
    'wizard.selectProfileDesc': 'Elija un perfil de riesgo que defina el comportamiento operacional y la agresividad de la estrategia de trading. Cada perfil tiene parámetros de riesgo preconfigurados.',
    'wizard.riskPerTrade': 'Riesgo/Trade',
    'wizard.maxPositions': 'Max Posiciones',
    'wizard.tpMultiplier': 'Take Profit',
    'wizard.noProfiles': 'No hay perfiles de riesgo disponibles. Contacte soporte.',
    'wizard.campaignName': 'Nombre de Campaña',
    'wizard.campaignNamePlaceholder': 'Mi Campaña de Diciembre',
    'wizard.initialCapital': 'Capital Inicial',
    'wizard.minCapitalHint': 'Mínimo $10 USD',
    'wizard.duration': 'Duración de Campaña',
    'wizard.days': 'días',
    'wizard.recommended': 'recomendado',
    'wizard.paperMode': 'Paper Trading',
    'wizard.paperModeDesc': 'Practique trading con dinero simulado. Sin riesgo real.',
    'wizard.liveMode': 'Trading Real',
    'wizard.liveModeDesc': 'Opere con dinero real en Kraken. Ganancias y pérdidas reales.',
    'wizard.noRiskBadge': 'Sin Riesgo',
    'wizard.realMoneyBadge': 'Dinero Real',
    'wizard.krakenValidation': 'Estado de API Kraken',
    'wizard.krakenValid': 'API Kraken configurada y válida',
    'wizard.krakenInvalid': 'API Kraken no configurada',
    'wizard.configureKraken': 'Configurar en Ajustes',
    'wizard.livePortfolioWarning': 'Este portafolio usa modo Trading Real',
    'wizard.noPortfolios': 'Sin portafolios disponibles. Cree uno primero.',
    'wizard.createPortfolio': 'Crear Portafolio',
    'wizard.maxDrawdown': 'Límite Máximo de Drawdown',
    'wizard.maxDrawdownDesc': 'La campaña se detendrá automáticamente si las pérdidas superan este porcentaje',
    'wizard.circuitBreaker': 'Circuit Breaker',
    'wizard.protectionsEnabled': 'Protecciones Habilitadas',
    'wizard.protection1': 'Sistema de circuit breaker de 3 capas (activo, cluster, global)',
    'wizard.protection2': 'Stop Loss y Take Profit basados en ATR',
    'wizard.protection3': 'Monitoreo de staleness en tiempo real',
    'wizard.mode': 'Modo de Trading',
    'wizard.portfolio': 'Portafolio',
    'wizard.readyToLaunch': 'Listo para Lanzar',
    'wizard.launchDescription': 'Su campaña comenzará inmediatamente después de la activación. Puede pausarla o detenerla en cualquier momento desde la página de Campañas.',
    'wizard.previous': 'Anterior',
    'wizard.next': 'Siguiente',
    'wizard.activateCampaign': 'Activar Campaña',
    'wizard.success': 'Éxito',
    'wizard.campaignCreated': '¡Su campaña ha sido creada y ahora está activa!',
    'wizard.createError': 'Error al crear la campaña. Por favor intente de nuevo.',
    'wizard.profilesLoadError': 'Error al cargar perfiles de riesgo. Por favor actualice la página.',
    'wizard.retry': 'Intentar de nuevo',
    'wizard.validation.nameRequired': 'Por favor ingrese un nombre de campaña',
    'wizard.validation.minCapital': 'El capital mínimo es $10 USD',
    'wizard.validation.krakenRequired': 'El modo real requiere credenciales de API Kraken válidas',
    'wizard.validation.portfolioRequired': 'Por favor seleccione un portafolio',
    'wizard.aiSuggest': 'Sugerencia IA',
    'wizard.aiSuggestionReady': 'Recomendación IA Lista',
    'wizard.aiSuggestionDesc': 'Revise los parámetros de riesgo sugeridos a continuación',
    'wizard.aiSuggestionError': 'Error al obtener sugerencia de IA',
    'wizard.aiRecommendation': 'Recomendación IA',
    'wizard.suggestedDrawdown': 'Drawdown Sugerido',
    'wizard.aiTips': 'Consejos',
    'wizard.applySuggestion': 'Aplicar Sugerencia',
    'wizard.suggestionApplied': 'Sugerencia Aplicada',
    'wizard.risk.conservative': 'Conservador',
    'wizard.risk.moderate': 'Moderado',
    'wizard.risk.aggressive': 'Agresivo',
    'wizard.market.status.healthy': 'Mercado Saludable',
    'wizard.market.status.warning': 'Alerta de Mercado',
    'wizard.market.status.critical': 'Mercado Critico',
    'wizard.market.dataQuality': 'Calidad de Datos',
    'wizard.market.activeSymbols': 'Simbolos Activos',
    'wizard.market.staleness': 'Latencia Promedio',
    'wizard.market.volatility': 'Volatilidad',
    'wizard.market.avgVolatility': 'Volatilidad Promedio',
    'wizard.market.level': 'Nivel',
    'wizard.market.circuitBreakers': 'Circuit Breakers',
    'wizard.market.tradingAllowed': 'Trading Permitido',
    'wizard.market.tradingBlocked': 'Trading Bloqueado',
    'wizard.market.topVolatile': 'Activos Mas Volatiles',
    'wizard.market.noData': 'Datos de mercado no disponibles',
    'wizard.aiAnalyzing': 'IA Analizando...',
    'wizard.aiAnalyzingDesc': 'Generando analisis de campana',
    'wizard.aiSummary': 'Analisis IA',
    'wizard.pros': 'Ventajas',
    'wizard.cons': 'Consideraciones',

    // Costs & Taxes
    'costs.title': 'Costos e Impuestos',
    'costs.subtitle': 'Rastree el impacto de los costos de trading y las obligaciones fiscales',
    'costs.impact': 'Análisis de Impacto de Costos',
    'costs.impactDescription': 'Vea cómo las comisiones, slippage e impuestos afectan sus ganancias',
    'costs.totalFees': 'Comisiones Totales',
    'costs.totalSlippage': 'Slippage Total',
    'costs.totalTaxes': 'Impuestos Totales',
    'costs.totalCosts': 'Costos Totales',
    'costs.netProfit': 'Ganancia Neta',
    'costs.grossProfit': 'Ganancia Bruta',
    'costs.impactOnProfit': 'Impacto en Ganancias',
    'costs.breakdown': 'Desglose de Costos',
    'costs.noData': 'No hay datos de costos disponibles para el período seleccionado',
    'costs.period': 'Período',
    'costs.trades': 'Operaciones',
    'costs.profitableTrades': 'Operaciones Rentables',
    'costs.effectiveRate': 'Tasa Efectiva de Impuestos',

    // Tax Profile
    'tax.profile': 'Perfil Fiscal',
    'tax.profileDescription': 'Configure sus ajustes fiscales según su país',
    'tax.country': 'País/Región',
    'tax.regime': 'Régimen Fiscal',
    'tax.year': 'Año Fiscal',
    'tax.shortTermRate': 'Tasa Corto Plazo',
    'tax.longTermRate': 'Tasa Largo Plazo',
    'tax.minimumTaxable': 'Mínimo Imponible',
    'tax.saveProfile': 'Guardar Perfil',
    'tax.profileSaved': 'Perfil fiscal guardado exitosamente',
    'tax.profileError': 'Error al guardar perfil fiscal',
    'tax.noProfile': 'No hay perfil fiscal configurado',
    'tax.suggestLocation': 'Sugerido según su ubicación',
    'tax.acceptSuggestion': 'Aceptar Sugerencia',
    'tax.configureManually': 'Configurar Manualmente',

    // Tax Regimes
    'tax.regime.BR': 'Brasil - Day Trading (15% diario)',
    'tax.regime.US': 'Estados Unidos - Ganancias de Capital',
    'tax.regime.EU': 'Unión Europea - Ganancias de Capital',
    'tax.regime.AE': 'EAU - Exento de Impuestos',
    'tax.regime.SG': 'Singapur - Exento de Impuestos',

    // Tooltips
    'tooltip.slippage': 'El slippage es la diferencia entre el precio esperado y el precio real de ejecución',
    'tooltip.makerFee': 'La comisión maker se cobra cuando agrega liquidez al libro de órdenes (órdenes límite)',
    'tooltip.takerFee': 'La comisión taker se cobra cuando retira liquidez del libro de órdenes (órdenes de mercado)',
    'tooltip.fees': 'Comisiones de trading cobradas por el exchange por ejecutar sus órdenes',
    'tooltip.taxes': 'Impuestos adeudados según su perfil fiscal y ganancias realizadas',
    'tooltip.netProfit': 'Ganancia final después de deducir comisiones, slippage e impuestos',
    'tooltip.grossProfit': 'Ganancia total antes de deducir costos e impuestos',
    'tooltip.dailyNetting': 'Régimen fiscal Brasil: Ganancias y pérdidas se compensan diariamente antes de calcular el 15%',
    'tooltip.perTrade': 'Impuesto calculado en cada operación individual basado en la ganancia realizada',
    'tooltip.taxExempt': 'Esta región no grava las ganancias de trading de criptomonedas',

    // Compliance Report
    'report.title': 'Informe de Cumplimiento',
    'report.description': 'Exporte informes detallados para declaración de impuestos y cumplimiento',
    'report.export': 'Exportar Informe',
    'report.exportCSV': 'Exportar CSV',
    'report.exportPDF': 'Exportar PDF',
    'report.generating': 'Generando informe...',
    'report.success': 'Informe generado exitosamente',
    'report.error': 'Error al generar informe',
    'report.period': 'Período del Informe',
    'report.summary': 'Resumen',
    'report.details': 'Detalles de Operaciones',

    // Operations (Runbook)
    'operations.title': 'Flujo Operacional',
    'operations.subtitle': 'Timeline del ciclo de trading diario y estado',
    'operations.never': 'Nunca',
    'operations.nextRebalance': 'Próximo Rebalance',
    'operations.assetsSelected': 'Activos Seleccionados',
    'operations.of100': 'de 100 máx',
    'operations.activePositions': 'Posiciones Activas',
    'operations.openPositions': 'Posiciones abiertas',
    'operations.dailyPnL': 'P&G Diario',
    'operations.today': 'Hoy',
    'operations.dataStatus': 'Estado de Datos',
    'operations.dataQuality': 'Calidad de datos',
    'operations.cycleProgress': 'Progreso del Ciclo',
    'operations.lastRun': 'Última ejecución',
    'operations.lastExecution': 'Hora de última ejecución',

    'operations.timeline.title': 'Timeline Diario del Runbook',
    'operations.timeline.description': 'Ciclo operacional: Selección, Distribución, Trading, Rebalance, Auditoría',

    'operations.selection.title': 'Selección Global',
    'operations.selection.description': 'Ejecutar ranking + clustering K-means para seleccionar los top 100 activos',
    'operations.distribution.title': 'Distribución',
    'operations.distribution.description': 'Calcular sizing con costos (Fee_avg, Slippage_avg), aplicar caps por cluster y globales',
    'operations.trading.title': 'Trading',
    'operations.trading.time': 'Durante el día',
    'operations.trading.description': 'Señales, órdenes OCO, stops, trailing, reasignación de lucros, monitoreo de staleness',
    'operations.rebalance.title': 'Rebalance',
    'operations.rebalance.time': 'Cada 8h',
    'operations.rebalance.description': 'Re-ranking, intercambio de activos, recalcular posiciones',
    'operations.audit.title': 'Auditoría',
    'operations.audit.time': 'Cada 24h',
    'operations.audit.description': 'Métricas de performance: hit rate, payoff, PnL, VaR/ES, costos, slippage',

    'operations.status.completed': 'Listo',
    'operations.status.active': 'Activo',
    'operations.status.degraded': 'Degradado',
    'operations.status.pending': 'Pendiente',

    'operations.staleness.fresh': 'Fresco',
    'operations.staleness.warn': 'Alerta',
    'operations.staleness.hard': 'Obsoleto',
    'operations.staleness.kill_switch': 'Crítico',

    'operations.tradingWindow.title': 'Ventana de Trading',
    'operations.tradingWindow.signals': 'Generación de Señales',
    'operations.tradingWindow.active': 'Activo',
    'operations.tradingWindow.paused': 'Pausado',
    'operations.tradingWindow.oco': 'Órdenes OCO',
    'operations.tradingWindow.ocoEnabled': 'Habilitado',
    'operations.tradingWindow.staleness': 'Monitor de Staleness',

    'operations.rebalanceInfo.title': 'Cronograma de Rebalance',
    'operations.rebalanceInfo.interval': 'Intervalo',
    'operations.rebalanceInfo.lastRun': 'Última Ejecución',
    'operations.rebalanceInfo.nextRun': 'Próxima Ejecución',

    // Audit Dashboard
    'audit.title': 'Panel de Auditoría',
    'audit.subtitle': 'Métricas de rendimiento consolidadas de 24 horas',
    'audit.period': 'Período',
    'audit.performance': 'Métricas de Rendimiento',
    'audit.hitRate': 'Tasa de Acierto',
    'audit.trades': 'operaciones',
    'audit.wins': 'ganancias',
    'audit.losses': 'pérdidas',
    'audit.profitFactor': 'Factor de Ganancia',
    'audit.excellent': 'Excelente',
    'audit.good': 'Bueno',
    'audit.poor': 'Pobre',
    'audit.avgWin': 'Gan. Promedio',
    'audit.avgLoss': 'Pérd. Promedio',
    'audit.pnlSection': 'Resumen de P&G',
    'audit.totalPnL': 'P&G Total',
    'audit.realized': 'Realizado',
    'audit.unrealized': 'No Realizado',
    'audit.equity': 'Capital Actual',
    'audit.riskSection': 'Métricas de Riesgo',
    'audit.var95': 'VaR 95%',
    'audit.var95Desc': 'Pérdida peor caso 5%',
    'audit.expectedShortfall': 'Pérdida Esperada',
    'audit.esDesc': 'Pérdida promedio de cola',
    'audit.maxDrawdown': 'Drawdown Máximo',
    'audit.drawdownDesc': 'Caída pico a valle',
    'audit.costsSection': 'Costos de Trading',
    'audit.totalFees': 'Comisiones Totales',
    'audit.slippage': 'Deslizamiento',
    'audit.totalCosts': 'Costos Totales',
    'audit.costPerTrade': 'Costo por Operación',
    'audit.lastUpdated': 'Última actualización',
    
    // Backtest translations
    'backtest.title': 'Backtest y Simulación',
    'backtest.subtitle': 'Pruebas históricas con análisis de estrés Monte Carlo',
    'backtest.newBacktest': 'Nuevo Backtest',
    'backtest.history': 'Historial de Backtest',
    'backtest.configuration': 'Configuración',
    'backtest.name': 'Nombre del Backtest',
    'backtest.namePlaceholder': 'Mi análisis de backtest',
    'backtest.period': 'Período de Análisis',
    'backtest.startDate': 'Fecha de Inicio',
    'backtest.endDate': 'Fecha de Fin',
    'backtest.initialCapital': 'Capital Inicial',
    'backtest.symbols': 'Símbolos',
    'backtest.symbolsPlaceholder': 'BTC/USD, ETH/USD',
    'backtest.applyBreakers': 'Aplicar Circuit Breakers',
    'backtest.applyBreakersDesc': 'Habilitar gestión de riesgo de 3 capas (activo, cluster, global)',
    'backtest.strategyParams': 'Parámetros de Estrategia',
    'backtest.riskParams': 'Parámetros de Riesgo',
    'backtest.costParams': 'Parámetros de Costo',
    'backtest.runBacktest': 'Ejecutar Backtest',
    'backtest.running': 'Ejecutando...',
    'backtest.status': 'Estado',
    'backtest.pending': 'Pendiente',
    'backtest.completed': 'Completado',
    'backtest.failed': 'Fallido',
    'backtest.progress': 'Progreso',
    'backtest.results': 'Resultados',
    'backtest.noBacktests': 'Sin backtests aún. Ejecute su primera simulación arriba.',
    'backtest.metrics.title': 'Métricas de Rendimiento',
    'backtest.metrics.hitRate': 'Tasa de Acierto',
    'backtest.metrics.profitFactor': 'Factor de Ganancia',
    'backtest.metrics.payoffRatio': 'Ratio de Pago',
    'backtest.metrics.expectancy': 'Esperanza',
    'backtest.metrics.avgWin': 'Gan. Promedio',
    'backtest.metrics.avgLoss': 'Pérd. Promedio',
    'backtest.metrics.sharpe': 'Ratio Sharpe',
    'backtest.metrics.sortino': 'Ratio Sortino',
    'backtest.metrics.var95': 'VaR 95%',
    'backtest.metrics.var99': 'VaR 99%',
    'backtest.metrics.es95': 'ES 95%',
    'backtest.metrics.es99': 'ES 99%',
    'backtest.metrics.maxDrawdown': 'Drawdown Máximo',
    'backtest.metrics.turnover': 'Rotación',
    'backtest.metrics.fees': 'Comisiones',
    'backtest.metrics.slippage': 'Deslizamiento',
    'backtest.metrics.costDrag': 'Arrastre de Costos',
    'backtest.monteCarlo.title': 'Simulación Monte Carlo',
    'backtest.monteCarlo.scenarios': 'Escenarios',
    'backtest.monteCarlo.meanEquity': 'Capital Final Medio',
    'backtest.monteCarlo.stdEquity': 'Desv. Est. Capital',
    'backtest.monteCarlo.probPositive': 'Prob. PnL Positivo',
    'backtest.monteCarlo.probExceed10DD': 'Prob. >10% Drawdown',
    'backtest.monteCarlo.confidenceInterval': 'Intervalo de Confianza 95%',
    'backtest.validation.title': 'Criterios de Validación',
    'backtest.validation.es95Improved': 'ES95 Mejorado con Breakers',
    'backtest.validation.var99Improved': 'VaR99 Reducido en Estrés',
    'backtest.validation.pnlPositive': 'PnL Neto Positivo',
    'backtest.validation.passed': 'Validación APROBADA',
    'backtest.validation.failed': 'Validación FALLIDA',
    'backtest.validation.notes': 'Notas de Validación',
    'backtest.breakers.title': 'Estadísticas de Circuit Breakers',
    'backtest.breakers.assetTriggered': 'Breakers de Activo Activados',
    'backtest.breakers.clusterTriggered': 'Breakers de Cluster Activados',
    'backtest.breakers.globalTriggered': 'Breakers Globales Activados',
    'backtest.breakers.tradesBlocked': 'Operaciones Bloqueadas',
    'backtest.trades.title': 'Operaciones Recientes',
    'backtest.trades.symbol': 'Símbolo',
    'backtest.trades.side': 'Lado',
    'backtest.trades.entry': 'Entrada',
    'backtest.trades.exit': 'Salida',
    'backtest.trades.pnl': 'PnL',
    'backtest.trades.reason': 'Razón de Salida',

    // Robot Activity Feed
    'robot.feed.title': 'Actividad del Robot',
    'robot.feed.empty': 'Sin actividad del robot aún',
    'robot.feed.waiting': 'Esperando señales de trading...',
    'robot.feed.error': 'Error al cargar actividades',
    'robot.severity.success': 'Éxito',
    'robot.severity.warning': 'Advertencia',
    'robot.severity.error': 'Error',
    'robot.severity.info': 'Info',
    'robot.signal.long': 'Señal LONG detectada',
    'robot.signal.short': 'Señal SHORT detectada',
    'robot.signal.neutral': 'Sin señal (neutral)',
    'robot.position.open.long': 'Posición LONG abierta',
    'robot.position.open.short': 'Posición SHORT abierta',
    'robot.position.close.sl_hit': 'Posición cerrada - Stop Loss alcanzado',
    'robot.position.close.tp_hit': 'Posición cerrada - Take Profit alcanzado',
    'robot.position.close.signal_exit': 'Posición cerrada - Salida por señal',
    'robot.position.close.rebalance_exit': 'Posición cerrada - Rebalanceo',
    'robot.position.close.breaker_exit': 'Posición cerrada - Circuit breaker',
    'robot.position.close.manual': 'Posición cerrada - Manual',
    'robot.breaker.pair.triggered': 'Circuit breaker de par ACTIVADO',
    'robot.breaker.pair.warning': 'Advertencia de circuit breaker de par',
    'robot.breaker.daily.triggered': 'Circuit breaker diario ACTIVADO',
    'robot.breaker.daily.warning': 'Advertencia de límite de pérdida diaria',
    'robot.breaker.campaign.triggered': 'Circuit breaker de campaña ACTIVADO',
    'robot.breaker.campaign.warning': 'Advertencia de límite de drawdown',
    'robot.rebalance.complete': 'Rebalanceo de 8 horas completo',
    'robot.scan.signals_found': 'Escaneo de mercado: Señales encontradas',
    'robot.scan.no_signals': 'Escaneo de mercado: Sin señales',
    'robot.details.signal': 'Señal',
    'robot.details.price': 'Precio',
    'robot.details.side': 'Lado',
    'robot.details.entry': 'Entrada',
    'robot.details.exit': 'Salida',
    'robot.details.reason': 'Razón',
    'robot.details.type': 'Tipo',
    'robot.details.threshold': 'Umbral',
    'robot.details.current': 'Actual',
    'robot.details.tradable': 'Activos negociables',
    'robot.details.added': 'Agregados',
    'robot.details.removed': 'Eliminados',
    'robot.details.scanned': 'Escaneados',
    'robot.details.signals': 'Señales',
    'campaignDetail.tabs.activity': 'Actividad',
  },
  'pt-BR': {
    // Navigation
    'nav.dashboard': 'Painel',
    'nav.trading': 'Negociacao',
    'nav.positions': 'Posicoes',
    'nav.performance': 'Desempenho',
    'nav.portfolios': 'Carteiras',
    'nav.risk': 'Gestao de Risco',
    'nav.news': 'Noticias',
    'nav.assets': 'Selecao de Ativos',
    'nav.operations': 'Operacoes',
    'nav.audit': 'Auditoria',
    'nav.backtest': 'Backtest',
    'nav.settings': 'Configuracoes',
    'nav.admin': 'Admin',
    'nav.logout': 'Sair',
    
    // Admin Dashboard
    'admin.title': 'Painel de Administração',
    'admin.overview': 'Visão Geral da Plataforma',
    'admin.users_total': 'Usuários Totais',
    'admin.users_beta': 'Usuários Beta',
    'admin.users_admins': 'Administradores',
    'admin.beta_codes': 'Códigos Beta',
    'admin.codes_active': 'Códigos Ativos',
    'admin.codes_used': 'Usos Totais',
    'admin.emails_title': 'Emails Autorizados',
    'admin.emails_description': 'Emails pré-aprovados para acesso beta',
    'admin.email_add': 'Adicionar Email',
    'admin.email_placeholder': 'email@exemplo.com',
    'admin.notes_placeholder': 'Notas opcionais',
    'admin.users_title': 'Usuários',
    'admin.users_description': 'Gerenciar usuários da plataforma',
    'admin.codes_title': 'Códigos Beta',
    'admin.codes_description': 'Gerenciar códigos de convite beta',
    'admin.code_add': 'Criar Código',
    'admin.code_placeholder': 'ex. DELFOS-VIP-001',
    'admin.max_uses': 'Usos Máx',
    'admin.expires': 'Expira',
    'admin.current_uses': 'Usos',
    'admin.status': 'Status',
    'admin.active': 'Ativo',
    'admin.inactive': 'Inativo',
    'admin.actions': 'Ações',
    'admin.deactivate': 'Desativar',
    'admin.remove': 'Remover',
    'admin.approve': 'Aprovar Beta',
    'admin.make_admin': 'Tornar Admin',
    'admin.remove_admin': 'Remover Admin',
    'admin.no_emails': 'Nenhum email autorizado',
    'admin.no_codes': 'Nenhum código beta',
    'admin.no_users': 'Nenhum usuário encontrado',
    'admin.added_by': 'Adicionado por',
    'admin.created_at': 'Criado',
    'admin.never_expires': 'Nunca',
    
    // Dashboard
    'dashboard.title': 'Painel',
    'dashboard.portfolio_value': 'Valor da Carteira',
    'dashboard.daily_pnl': 'L&P Diário',
    'dashboard.active_positions': 'Posições Ativas',
    'dashboard.total_trades': 'Total de Negociações',
    'dashboard.active_portfolios': 'Carteiras ativas',
    'dashboard.no_active_portfolio': 'Nenhuma carteira ativa',
    'dashboard.active_campaigns': 'Campanhas Ativas',
    'dashboard.open_positions': 'Posições Abertas',
    'dashboard.robots_trading': 'Robôs operando automaticamente',
    'dashboard.across_campaigns': 'Em todas as campanhas',
    'dashboard.quick_actions': 'Ações Rápidas',
    'dashboard.new_campaign': 'Nova Campanha',
    'dashboard.view_campaigns': 'Ver Campanhas',
    'dashboard.settings': 'Configurações',
    'dashboard.recent_campaigns': 'Campanhas Recentes',
    'dashboard.view_all': 'Ver Todas',
    'dashboard.no_campaigns': 'Nenhuma campanha ainda',
    'dashboard.create_first': 'Crie sua primeira campanha',
    'dashboard.robot_activity': 'Atividade do Robô',
    'dashboard.no_activity': 'Sem atividade recente',
    'dashboard.market_overview': 'Visão do Mercado',
    'dashboard.campaigns.running': 'Em Execução',
    'dashboard.campaigns.paused': 'Pausada',
    'dashboard.campaigns.completed': 'Concluída',
    'dashboard.campaigns.pending': 'Pendente',
    'dashboard.profile.C': 'Conservador',
    'dashboard.profile.M': 'Moderado',
    'dashboard.profile.A': 'Agressivo',
    'dashboard.profile.conservative': 'Conservador',
    'dashboard.profile.moderate': 'Moderado',
    'dashboard.profile.aggressive': 'Agressivo',
    
    // Trading
    'trading.title': 'Negociação',
    'trading.buy': 'Comprar',
    'trading.sell': 'Vender',
    'trading.price': 'Preço',
    'trading.amount': 'Quantidade',
    'trading.total': 'Total',
    'trading.order_book': 'Livro de Ofertas',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    'common.retry': 'Tentar Novamente',
    
    // Auth
    'auth.login': 'Entrar',
    'auth.welcome': 'Bem-vindo ao DELFOS',
    'auth.subtitle': 'Plataforma Profissional de Trading de Criptomoedas',

    // Asset Selection
    'assets.title': 'Seleção de Ativos',
    'assets.description': 'Selecionar os 100 pares de criptomoedas mais negociáveis usando filtros quantitativos e clustering',
    'assets.run_button': 'Executar Seleção',
    'assets.running': 'Executando...',
    'assets.last_run': 'Última Execução',
    'assets.never': 'Nunca',
    'assets.run_id': 'ID de Execução',
    'assets.assets_selected': 'Ativos Selecionados',
    'assets.clusters': 'Clusters',
    'assets.no_data': 'Nenhum dado disponível. Clique em "Executar Seleção" para começar.',
    'assets.success_title': 'Seleção Completa',
    'assets.success_message': 'Selecionados {selected} ativos de {total} candidatos, agrupados em {clusters} clusters.',
    'assets.error_title': 'Seleção Falhou',
    'assets.error_message': 'Falha ao executar a seleção de ativos',
    'assets.top_100_title': 'TOP 100 Ativos Classificados',
    'assets.rank': 'Classificação',
    'assets.symbol': 'Símbolo',
    'assets.score': 'Pontuação',
    'assets.cluster': 'Cluster',
    'assets.no_rankings': 'Nenhuma classificação disponível',
    'assets.running_title': 'Executando Seleção de Ativos',
    'assets.running_description': 'Analisando mais de 400 pares de criptomoedas com filtros quantitativos...',
    'assets.fetch_error': 'Falha ao buscar classificações',
    'assets.cluster_prefix': 'C',
    'assets.no_cluster': '-',
    'assets.visualization.title': 'Visualização de Clusters',
    'assets.visualization.description': 'Representação visual de clusters de ativos baseada em características quantitativas',
    'assets.visualization.rank': 'Classificação',
    'assets.visualization.score': 'Pontuação',
    'assets.visualization.cluster': 'Cluster',
    'assets.visualization.normalized_rank': 'Classificação Normalizada',
    'assets.visualization.unclustered': 'Sem Cluster',
    'assets.filters.title': 'Filtros de Negociabilidade',
    'assets.filters.description': 'Personalizar limites de volume, spread, profundidade e volatilidade para seleção de ativos',
    'assets.filters.customized': 'Personalizado',
    'assets.filters.reset': 'Restaurar',
    'assets.filters.show': 'Mostrar Filtros',
    'assets.filters.hide': 'Ocultar Filtros',
    'assets.filters.min_volume': 'Volume Mín (24h)',
    'assets.filters.max_spread': 'Spread Máx',
    'assets.filters.min_depth': 'Profundidade Mín do Livro',
    'assets.filters.min_atr': 'Volatilidade Diária Mín (ATR)',
    'assets.filters.default': 'Padrão',

    // Campaign
    'campaign.title': 'Campanhas',
    'campaign.subtitle': 'Gerencie e acompanhe suas campanhas de trading automatizado',
    'campaign.timeline': 'Cronograma da Campanha',
    'campaign.dayProgress': 'Progresso do Dia',
    'campaign.day': 'Dia',
    'campaign.daysRemaining': 'dias restantes',
    'campaign.initialCapital': 'Capital Inicial',
    'campaign.currentEquity': 'Capital Atual',
    'campaign.finalEquity': 'Capital Final',
    'campaign.totalPnL': 'L&P Total',
    'campaign.drawdown': 'Drawdown',
    'campaign.drawdownBreached': 'Limite de drawdown ultrapassado - Campanha parada',
    'campaign.activeMessage': 'Campanha em execução dentro dos parâmetros de risco',
    'campaign.errorLoading': 'Erro ao carregar métricas da campanha',
    'campaign.noCampaign': 'Nenhuma Campanha Ativa',
    'campaign.noCampaignDesc': 'Inicie uma nova campanha na página de Portfolios',
    'campaign.goToPortfolios': 'Ir para Portfolios',
    'campaign.history': 'Historico de Campanhas',
    'campaign.pause': 'Pausar',
    'campaign.resume': 'Retomar',
    'campaign.stop': 'Parar',
    'campaign.rebalance': 'Rebalancear',
    'campaign.paused': 'Campanha Pausada',
    'campaign.pausedDesc': 'A campanha foi pausada. Trading interrompido.',
    'campaign.resumed': 'Campanha Retomada',
    'campaign.resumedDesc': 'A campanha esta funcionando novamente.',
    'campaign.stopped': 'Campanha Parada',
    'campaign.stoppedDesc': 'A campanha foi encerrada permanentemente.',
    'campaign.rebalanced': 'Rebalanceamento Iniciado',
    'campaign.rebalancedDesc': 'O rebalanceamento do portfolio comecou.',
    'campaign.delete': 'Excluir',
    'campaign.deleted': 'Campanha Excluida',
    'campaign.deletedDesc': 'A campanha foi excluida permanentemente.',
    'campaign.deleteConfirmTitle': 'Excluir Campanha',
    'campaign.deleteConfirmDesc': 'Tem certeza que deseja excluir esta campanha? Esta acao nao pode ser desfeita.',
    'campaign.activeCampaigns': 'Campanhas Ativas',
    'campaign.pausedCampaigns': 'Campanhas Pausadas',
    'campaign.active': 'Ativa',
    'campaign.pausedStatus': 'Pausada',
    'campaign.stoppedStatus': 'Parada',
    'campaign.completedStatus': 'Concluida',
    'campaign.createNew': 'Criar Nova Campanha',
    'campaign.activeStatus': 'Ativa',
    'campaign.clusters': 'Clusters',
    'campaign.tradableAssets': 'negociáveis',

    // Campaign Detail
    'campaignDetail.notFound': 'Campanha não encontrada',
    'campaignDetail.backToCampaigns': 'Voltar para Campanhas',
    'campaignDetail.tabs.universe': 'Universo de Ativos',
    'campaignDetail.tabs.positions': 'Posições',
    'campaignDetail.tabs.reports': 'Relatórios Diários',
    'campaignDetail.universe.title': 'Universo de Ativos',
    'campaignDetail.universe.description': 'Ativos selecionados para esta campanha baseados em clustering K-means',
    'campaignDetail.universe.total': 'Total',
    'campaignDetail.universe.tradable': 'Negociáveis',
    'campaignDetail.universe.active': 'Ativos',
    'campaignDetail.universe.inactive': 'Inativos',
    'campaignDetail.universe.problematic': 'Problemáticos',
    'campaignDetail.universe.clusters': 'Clusters',
    'campaignDetail.universe.searchPlaceholder': 'Buscar ativos...',
    'campaignDetail.universe.filterStatus': 'Filtrar Status',
    'campaignDetail.universe.filterCluster': 'Filtrar Cluster',
    'campaignDetail.universe.allStatus': 'Todos os Status',
    'campaignDetail.universe.allClusters': 'Todos os Clusters',
    'campaignDetail.universe.noCluster': 'Sem Cluster',
    'campaignDetail.universe.rank': 'Ranking',
    'campaignDetail.universe.symbol': 'Símbolo',
    'campaignDetail.universe.cluster': 'Cluster',
    'campaignDetail.universe.score': 'Pontuação',
    'campaignDetail.universe.weight': 'Peso',
    'campaignDetail.universe.status': 'Status',
    'campaignDetail.universe.empty': 'Nenhum ativo no universo desta campanha',
    'campaignDetail.positions.title': 'Posições de Trading',
    'campaignDetail.positions.description': 'Posições abertas e fechadas desta campanha',
    'campaignDetail.positions.openPositions': 'Posições Abertas',
    'campaignDetail.positions.closedPositions': 'Posições Fechadas',
    'campaignDetail.positions.symbol': 'Símbolo',
    'campaignDetail.positions.side': 'Lado',
    'campaignDetail.positions.quantity': 'Quantidade',
    'campaignDetail.positions.entryPrice': 'Preço Entrada',
    'campaignDetail.positions.currentPrice': 'Preço Atual',
    'campaignDetail.positions.stopLoss': 'Stop Loss',
    'campaignDetail.positions.takeProfit': 'Take Profit',
    'campaignDetail.positions.unrealizedPnl': 'L&P Não Realizado',
    'campaignDetail.positions.realizedPnl': 'L&P Realizado',
    'campaignDetail.positions.openedAt': 'Aberta em',
    'campaignDetail.positions.closedAt': 'Fechada em',
    'campaignDetail.positions.closeReason': 'Razão de Fechamento',
    'campaignDetail.positions.noOpenPositions': 'Sem posições abertas',
    'campaignDetail.positions.noClosedPositions': 'Sem posições fechadas',
    'campaignDetail.positions.long': 'COMPRA',
    'campaignDetail.positions.short': 'VENDA',
    'campaignDetail.positions.tp': 'Take Profit',
    'campaignDetail.positions.sl': 'Stop Loss',
    'campaignDetail.positions.manual': 'Manual',
    'campaignDetail.positions.expired': 'Expirada',
    'campaignDetail.reports.comingSoon': 'Aba de relatórios em breve',

    // Campaign Wizard
    'wizard.title': 'Criar Nova Campanha',
    'wizard.subtitle': 'Siga os passos para configurar e lançar sua campanha de trading',
    'wizard.menuItem': 'Nova Campanha',
    'wizard.step.basics': 'Básico',
    'wizard.step.mode': 'Modo',
    'wizard.step.portfolio': 'Portfólio',
    'wizard.step.risk': 'Risco',
    'wizard.step.review': 'Revisar',
    'wizard.step1.title': 'Informações Básicas',
    'wizard.step1.description': 'Defina o nome, perfil, capital e duração da sua campanha',
    'wizard.step2.title': 'Modo de Trading',
    'wizard.step2.description': 'Escolha entre paper trading (simulação) ou trading real',
    'wizard.step3.title': 'Selecionar Portfólio',
    'wizard.step3.description': 'Escolha o portfólio com o qual esta campanha irá operar',
    'wizard.step4.title': 'Configuração de Risco',
    'wizard.step4.description': 'Configure seus limites de risco e limiares de circuit breaker',
    'wizard.step5.title': 'Revisar e Ativar',
    'wizard.step5.description': 'Revise suas configurações e análise IA antes de lançar',
    'wizard.selectProfile': 'Selecionar Perfil da Campanha',
    'wizard.selectProfileDesc': 'Escolha um perfil de risco que define o comportamento operacional e a agressividade da estratégia de trading. Cada perfil tem parâmetros de risco pré-configurados.',
    'wizard.riskPerTrade': 'Risco/Trade',
    'wizard.maxPositions': 'Max Posições',
    'wizard.tpMultiplier': 'Take Profit',
    'wizard.noProfiles': 'Nenhum perfil de risco disponível. Contate o suporte.',
    'wizard.campaignName': 'Nome da Campanha',
    'wizard.campaignNamePlaceholder': 'Minha Campanha de Dezembro',
    'wizard.initialCapital': 'Capital Inicial',
    'wizard.minCapitalHint': 'Mínimo $10 USD',
    'wizard.duration': 'Duração da Campanha',
    'wizard.days': 'dias',
    'wizard.recommended': 'recomendado',
    'wizard.paperMode': 'Paper Trading',
    'wizard.paperModeDesc': 'Pratique trading com dinheiro simulado. Sem risco real.',
    'wizard.liveMode': 'Trading Real',
    'wizard.liveModeDesc': 'Opere com dinheiro real na Kraken. Lucros e perdas reais.',
    'wizard.noRiskBadge': 'Sem Risco',
    'wizard.realMoneyBadge': 'Dinheiro Real',
    'wizard.krakenValidation': 'Status da API Kraken',
    'wizard.krakenValid': 'API Kraken configurada e válida',
    'wizard.krakenInvalid': 'API Kraken não configurada',
    'wizard.configureKraken': 'Configurar em Ajustes',
    'wizard.livePortfolioWarning': 'Este portfólio usa modo Trading Real',
    'wizard.noPortfolios': 'Sem portfólios disponíveis. Crie um primeiro.',
    'wizard.createPortfolio': 'Criar Portfólio',
    'wizard.maxDrawdown': 'Limite Máximo de Drawdown',
    'wizard.maxDrawdownDesc': 'A campanha será parada automaticamente se as perdas excederem esta porcentagem',
    'wizard.circuitBreaker': 'Circuit Breaker',
    'wizard.protectionsEnabled': 'Proteções Habilitadas',
    'wizard.protection1': 'Sistema de circuit breaker de 3 camadas (ativo, cluster, global)',
    'wizard.protection2': 'Stop Loss e Take Profit baseados em ATR',
    'wizard.protection3': 'Monitoramento de staleness em tempo real',
    'wizard.mode': 'Modo de Trading',
    'wizard.portfolio': 'Portfólio',
    'wizard.readyToLaunch': 'Pronto para Lançar',
    'wizard.launchDescription': 'Sua campanha começará imediatamente após a ativação. Você pode pausá-la ou pará-la a qualquer momento na página de Campanhas.',
    'wizard.previous': 'Anterior',
    'wizard.next': 'Próximo',
    'wizard.activateCampaign': 'Ativar Campanha',
    'wizard.success': 'Sucesso',
    'wizard.campaignCreated': 'Sua campanha foi criada e agora está ativa!',
    'wizard.createError': 'Falha ao criar campanha. Por favor tente novamente.',
    'wizard.profilesLoadError': 'Falha ao carregar perfis de risco. Por favor atualize a página.',
    'wizard.retry': 'Tentar novamente',
    'wizard.validation.nameRequired': 'Por favor insira um nome para a campanha',
    'wizard.validation.minCapital': 'O capital mínimo é $10 USD',
    'wizard.validation.krakenRequired': 'O modo real requer credenciais de API Kraken válidas',
    'wizard.validation.portfolioRequired': 'Por favor selecione um portfólio',
    'wizard.aiSuggest': 'Sugestão IA',
    'wizard.aiSuggestionReady': 'Recomendação IA Pronta',
    'wizard.aiSuggestionDesc': 'Revise os parâmetros de risco sugeridos abaixo',
    'wizard.aiSuggestionError': 'Falha ao obter sugestão da IA',
    'wizard.aiRecommendation': 'Recomendação IA',
    'wizard.suggestedDrawdown': 'Drawdown Sugerido',
    'wizard.aiTips': 'Dicas',
    'wizard.applySuggestion': 'Aplicar Sugestão',
    'wizard.suggestionApplied': 'Sugestão Aplicada',
    'wizard.risk.conservative': 'Conservador',
    'wizard.risk.moderate': 'Moderado',
    'wizard.risk.aggressive': 'Agressivo',
    'wizard.market.status.healthy': 'Mercado Saudável',
    'wizard.market.status.warning': 'Alerta de Mercado',
    'wizard.market.status.critical': 'Mercado Crítico',
    'wizard.market.dataQuality': 'Qualidade dos Dados',
    'wizard.market.activeSymbols': 'Símbolos Ativos',
    'wizard.market.staleness': 'Latência Média',
    'wizard.market.volatility': 'Volatilidade',
    'wizard.market.avgVolatility': 'Volatilidade Média',
    'wizard.market.level': 'Nível',
    'wizard.market.circuitBreakers': 'Circuit Breakers',
    'wizard.market.tradingAllowed': 'Trading Permitido',
    'wizard.market.tradingBlocked': 'Trading Bloqueado',
    'wizard.market.topVolatile': 'Ativos Mais Voláteis',
    'wizard.market.noData': 'Dados de mercado indisponíveis',
    'wizard.aiAnalyzing': 'IA Analisando...',
    'wizard.aiAnalyzingDesc': 'Gerando análise da campanha',
    'wizard.aiSummary': 'Análise IA',
    'wizard.pros': 'Vantagens',
    'wizard.cons': 'Considerações',

    // Costs & Taxes
    'costs.title': 'Custos e Impostos',
    'costs.subtitle': 'Acompanhe o impacto dos custos de trading e obrigações fiscais',
    'costs.impact': 'Análise de Impacto de Custos',
    'costs.impactDescription': 'Veja como taxas, slippage e impostos afetam seus lucros',
    'costs.totalFees': 'Taxas Totais',
    'costs.totalSlippage': 'Slippage Total',
    'costs.totalTaxes': 'Impostos Totais',
    'costs.totalCosts': 'Custos Totais',
    'costs.netProfit': 'Lucro Líquido',
    'costs.grossProfit': 'Lucro Bruto',
    'costs.impactOnProfit': 'Impacto no Lucro',
    'costs.breakdown': 'Detalhamento de Custos',
    'costs.noData': 'Nenhum dado de custos disponível para o período selecionado',
    'costs.period': 'Período',
    'costs.trades': 'Operações',
    'costs.profitableTrades': 'Operações Lucrativas',
    'costs.effectiveRate': 'Taxa Efetiva de Impostos',

    // Tax Profile
    'tax.profile': 'Perfil Fiscal',
    'tax.profileDescription': 'Configure suas definições fiscais de acordo com seu país',
    'tax.country': 'País/Região',
    'tax.regime': 'Regime Tributário',
    'tax.year': 'Ano Fiscal',
    'tax.shortTermRate': 'Taxa Curto Prazo',
    'tax.longTermRate': 'Taxa Longo Prazo',
    'tax.minimumTaxable': 'Mínimo Tributável',
    'tax.saveProfile': 'Salvar Perfil',
    'tax.profileSaved': 'Perfil fiscal salvo com sucesso',
    'tax.profileError': 'Erro ao salvar perfil fiscal',
    'tax.noProfile': 'Nenhum perfil fiscal configurado',
    'tax.suggestLocation': 'Sugerido com base na sua localização',
    'tax.acceptSuggestion': 'Aceitar Sugestão',
    'tax.configureManually': 'Configurar Manualmente',

    // Tax Regimes
    'tax.regime.BR': 'Brasil - Day Trading (15% diário)',
    'tax.regime.US': 'Estados Unidos - Ganhos de Capital',
    'tax.regime.EU': 'União Europeia - Ganhos de Capital',
    'tax.regime.AE': 'Emirados Árabes - Isento de Impostos',
    'tax.regime.SG': 'Singapura - Isento de Impostos',

    // Tooltips
    'tooltip.slippage': 'Slippage é a diferença entre o preço esperado e o preço real de execução',
    'tooltip.makerFee': 'Taxa maker é cobrada quando você adiciona liquidez ao livro de ofertas (ordens limitadas)',
    'tooltip.takerFee': 'Taxa taker é cobrada quando você remove liquidez do livro de ofertas (ordens a mercado)',
    'tooltip.fees': 'Taxas de trading cobradas pela exchange por executar suas ordens',
    'tooltip.taxes': 'Impostos devidos com base no seu perfil fiscal e lucros realizados',
    'tooltip.netProfit': 'Lucro final após deduzir taxas, slippage e impostos',
    'tooltip.grossProfit': 'Lucro total antes de deduzir custos e impostos',
    'tooltip.dailyNetting': 'Regime fiscal Brasil: Lucros e prejuízos são compensados diariamente antes de calcular os 15%',
    'tooltip.perTrade': 'Imposto calculado em cada operação individual com base no lucro realizado',
    'tooltip.taxExempt': 'Esta região não tributa lucros de trading de criptomoedas',

    // Compliance Report
    'report.title': 'Relatório de Compliance',
    'report.description': 'Exporte relatórios detalhados para declaração de impostos e compliance',
    'report.export': 'Exportar Relatório',
    'report.exportCSV': 'Exportar CSV',
    'report.exportPDF': 'Exportar PDF',
    'report.generating': 'Gerando relatório...',
    'report.success': 'Relatório gerado com sucesso',
    'report.error': 'Falha ao gerar relatório',
    'report.period': 'Período do Relatório',
    'report.summary': 'Resumo',
    'report.details': 'Detalhes das Operações',

    // Operations (Runbook)
    'operations.title': 'Fluxo Operacional',
    'operations.subtitle': 'Timeline do ciclo de trading diário e status',
    'operations.never': 'Nunca',
    'operations.nextRebalance': 'Próximo Rebalance',
    'operations.assetsSelected': 'Ativos Selecionados',
    'operations.of100': 'de 100 máx',
    'operations.activePositions': 'Posições Ativas',
    'operations.openPositions': 'Posições abertas',
    'operations.dailyPnL': 'L&P Diário',
    'operations.today': 'Hoje',
    'operations.dataStatus': 'Status dos Dados',
    'operations.dataQuality': 'Qualidade dos dados',
    'operations.cycleProgress': 'Progresso do Ciclo',
    'operations.lastRun': 'Última execução',
    'operations.lastExecution': 'Horário da última execução',

    'operations.timeline.title': 'Timeline Diário do Runbook',
    'operations.timeline.description': 'Ciclo operacional: Seleção, Distribuição, Trading, Rebalance, Auditoria',

    'operations.selection.title': 'Seleção Global',
    'operations.selection.description': 'Executar ranking + clustering K-means para selecionar os top 100 ativos',
    'operations.distribution.title': 'Distribuição',
    'operations.distribution.description': 'Calcular sizing com custos (Fee_avg, Slippage_avg), aplicar caps por cluster e globais',
    'operations.trading.title': 'Negociação',
    'operations.trading.time': 'Ao longo do dia',
    'operations.trading.description': 'Sinais, ordens OCO, stops, trailing, realocação de lucros, monitoração de staleness',
    'operations.rebalance.title': 'Rebalance',
    'operations.rebalance.time': 'A cada 8h',
    'operations.rebalance.description': 'Re-ranking, troca de ativos, recalcular posições',
    'operations.audit.title': 'Auditoria',
    'operations.audit.time': 'A cada 24h',
    'operations.audit.description': 'Métricas de performance: hit rate, payoff, PnL, VaR/ES, custos, slippage',

    'operations.status.completed': 'Concluído',
    'operations.status.active': 'Ativo',
    'operations.status.degraded': 'Degradado',
    'operations.status.pending': 'Pendente',

    'operations.staleness.fresh': 'Atualizado',
    'operations.staleness.warn': 'Alerta',
    'operations.staleness.hard': 'Obsoleto',
    'operations.staleness.kill_switch': 'Crítico',

    'operations.tradingWindow.title': 'Janela de Negociação',
    'operations.tradingWindow.signals': 'Geração de Sinais',
    'operations.tradingWindow.active': 'Ativo',
    'operations.tradingWindow.paused': 'Pausado',
    'operations.tradingWindow.oco': 'Ordens OCO',
    'operations.tradingWindow.ocoEnabled': 'Habilitado',
    'operations.tradingWindow.staleness': 'Monitor de Staleness',

    'operations.rebalanceInfo.title': 'Cronograma de Rebalance',
    'operations.rebalanceInfo.interval': 'Intervalo',
    'operations.rebalanceInfo.lastRun': 'Última Execução',
    'operations.rebalanceInfo.nextRun': 'Próxima Execução',

    // Audit Dashboard
    'audit.title': 'Painel de Auditoria',
    'audit.subtitle': 'Métricas de performance consolidadas de 24 horas',
    'audit.period': 'Período',
    'audit.performance': 'Métricas de Performance',
    'audit.hitRate': 'Taxa de Acerto',
    'audit.trades': 'operações',
    'audit.wins': 'ganhos',
    'audit.losses': 'perdas',
    'audit.profitFactor': 'Fator de Lucro',
    'audit.excellent': 'Excelente',
    'audit.good': 'Bom',
    'audit.poor': 'Ruim',
    'audit.avgWin': 'Ganho Médio',
    'audit.avgLoss': 'Perda Média',
    'audit.pnlSection': 'Resumo de L&P',
    'audit.totalPnL': 'L&P Total',
    'audit.realized': 'Realizado',
    'audit.unrealized': 'Não Realizado',
    'audit.equity': 'Capital Atual',
    'audit.riskSection': 'Métricas de Risco',
    'audit.var95': 'VaR 95%',
    'audit.var95Desc': 'Perda pior caso 5%',
    'audit.expectedShortfall': 'Perda Esperada',
    'audit.esDesc': 'Perda média da cauda',
    'audit.maxDrawdown': 'Drawdown Máximo',
    'audit.drawdownDesc': 'Queda pico ao vale',
    'audit.costsSection': 'Custos de Negociação',
    'audit.totalFees': 'Taxas Totais',
    'audit.slippage': 'Deslizamento',
    'audit.totalCosts': 'Custos Totais',
    'audit.costPerTrade': 'Custo por Operação',
    'audit.lastUpdated': 'Última atualização',
    
    // Backtest translations
    'backtest.title': 'Backtest e Simulação',
    'backtest.subtitle': 'Testes históricos com análise de estresse Monte Carlo',
    'backtest.newBacktest': 'Novo Backtest',
    'backtest.history': 'Histórico de Backtest',
    'backtest.configuration': 'Configuração',
    'backtest.name': 'Nome do Backtest',
    'backtest.namePlaceholder': 'Minha análise de backtest',
    'backtest.period': 'Período de Análise',
    'backtest.startDate': 'Data de Início',
    'backtest.endDate': 'Data de Fim',
    'backtest.initialCapital': 'Capital Inicial',
    'backtest.symbols': 'Símbolos',
    'backtest.symbolsPlaceholder': 'BTC/USD, ETH/USD',
    'backtest.applyBreakers': 'Aplicar Circuit Breakers',
    'backtest.applyBreakersDesc': 'Habilitar gestão de risco de 3 camadas (ativo, cluster, global)',
    'backtest.strategyParams': 'Parâmetros de Estratégia',
    'backtest.riskParams': 'Parâmetros de Risco',
    'backtest.costParams': 'Parâmetros de Custo',
    'backtest.runBacktest': 'Executar Backtest',
    'backtest.running': 'Executando...',
    'backtest.status': 'Status',
    'backtest.pending': 'Pendente',
    'backtest.completed': 'Concluído',
    'backtest.failed': 'Falhou',
    'backtest.progress': 'Progresso',
    'backtest.results': 'Resultados',
    'backtest.noBacktests': 'Nenhum backtest ainda. Execute sua primeira simulação acima.',
    'backtest.metrics.title': 'Métricas de Performance',
    'backtest.metrics.hitRate': 'Taxa de Acerto',
    'backtest.metrics.profitFactor': 'Fator de Lucro',
    'backtest.metrics.payoffRatio': 'Razão de Payoff',
    'backtest.metrics.expectancy': 'Expectativa',
    'backtest.metrics.avgWin': 'Ganho Médio',
    'backtest.metrics.avgLoss': 'Perda Média',
    'backtest.metrics.sharpe': 'Índice Sharpe',
    'backtest.metrics.sortino': 'Índice Sortino',
    'backtest.metrics.var95': 'VaR 95%',
    'backtest.metrics.var99': 'VaR 99%',
    'backtest.metrics.es95': 'ES 95%',
    'backtest.metrics.es99': 'ES 99%',
    'backtest.metrics.maxDrawdown': 'Drawdown Máximo',
    'backtest.metrics.turnover': 'Giro',
    'backtest.metrics.fees': 'Taxas',
    'backtest.metrics.slippage': 'Deslizamento',
    'backtest.metrics.costDrag': 'Arrasto de Custo',
    'backtest.monteCarlo.title': 'Simulação Monte Carlo',
    'backtest.monteCarlo.scenarios': 'Cenários',
    'backtest.monteCarlo.meanEquity': 'Capital Final Médio',
    'backtest.monteCarlo.stdEquity': 'Desvio Padrão Capital',
    'backtest.monteCarlo.probPositive': 'Prob. PnL Positivo',
    'backtest.monteCarlo.probExceed10DD': 'Prob. >10% Drawdown',
    'backtest.monteCarlo.confidenceInterval': 'Intervalo de Confiança 95%',
    'backtest.validation.title': 'Critérios de Validação',
    'backtest.validation.es95Improved': 'ES95 Melhorado com Breakers',
    'backtest.validation.var99Improved': 'VaR99 Reduzido em Estresse',
    'backtest.validation.pnlPositive': 'PnL Líquido Positivo',
    'backtest.validation.passed': 'Validação APROVADA',
    'backtest.validation.failed': 'Validação REPROVADA',
    'backtest.validation.notes': 'Notas de Validação',
    'backtest.breakers.title': 'Estatísticas de Circuit Breakers',
    'backtest.breakers.assetTriggered': 'Breakers de Ativo Acionados',
    'backtest.breakers.clusterTriggered': 'Breakers de Cluster Acionados',
    'backtest.breakers.globalTriggered': 'Breakers Globais Acionados',
    'backtest.breakers.tradesBlocked': 'Operações Bloqueadas',
    'backtest.trades.title': 'Operações Recentes',
    'backtest.trades.symbol': 'Símbolo',
    'backtest.trades.side': 'Lado',
    'backtest.trades.entry': 'Entrada',
    'backtest.trades.exit': 'Saída',
    'backtest.trades.pnl': 'L&P',
    'backtest.trades.reason': 'Razão da Saída',

    // Robot Activity Feed
    'robot.feed.title': 'Atividade do Robô',
    'robot.feed.empty': 'Sem atividade do robô ainda',
    'robot.feed.waiting': 'Aguardando sinais de trading...',
    'robot.feed.error': 'Erro ao carregar atividades',
    'robot.severity.success': 'Sucesso',
    'robot.severity.warning': 'Aviso',
    'robot.severity.error': 'Erro',
    'robot.severity.info': 'Info',
    'robot.signal.long': 'Sinal LONG detectado',
    'robot.signal.short': 'Sinal SHORT detectado',
    'robot.signal.neutral': 'Sem sinal (neutro)',
    'robot.position.open.long': 'Posição LONG aberta',
    'robot.position.open.short': 'Posição SHORT aberta',
    'robot.position.close.sl_hit': 'Posição fechada - Stop Loss atingido',
    'robot.position.close.tp_hit': 'Posição fechada - Take Profit atingido',
    'robot.position.close.signal_exit': 'Posição fechada - Saída por sinal',
    'robot.position.close.rebalance_exit': 'Posição fechada - Rebalanceamento',
    'robot.position.close.breaker_exit': 'Posição fechada - Circuit breaker',
    'robot.position.close.manual': 'Posição fechada - Manual',
    'robot.breaker.pair.triggered': 'Circuit breaker de par ACIONADO',
    'robot.breaker.pair.warning': 'Aviso de circuit breaker de par',
    'robot.breaker.daily.triggered': 'Circuit breaker diário ACIONADO',
    'robot.breaker.daily.warning': 'Aviso de limite de perda diária',
    'robot.breaker.campaign.triggered': 'Circuit breaker de campanha ACIONADO',
    'robot.breaker.campaign.warning': 'Aviso de limite de drawdown',
    'robot.rebalance.complete': 'Rebalanceamento de 8 horas completo',
    'robot.scan.signals_found': 'Varredura de mercado: Sinais encontrados',
    'robot.scan.no_signals': 'Varredura de mercado: Sem sinais',
    'robot.details.signal': 'Sinal',
    'robot.details.price': 'Preço',
    'robot.details.side': 'Lado',
    'robot.details.entry': 'Entrada',
    'robot.details.exit': 'Saída',
    'robot.details.reason': 'Razão',
    'robot.details.type': 'Tipo',
    'robot.details.threshold': 'Limite',
    'robot.details.current': 'Atual',
    'robot.details.tradable': 'Ativos negociáveis',
    'robot.details.added': 'Adicionados',
    'robot.details.removed': 'Removidos',
    'robot.details.scanned': 'Escaneados',
    'robot.details.signals': 'Sinais',
    'campaignDetail.tabs.activity': 'Atividade',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
